// Bonus conversation lessons (outside the main textbook sequence). Shipped as drafts:
// teachers can publish them in Admin > 학습 콘텐츠 when students finish the Hangeul course.

const v = (ko, roman, en, emoji = '') => ({ ko, roman, en, emoji });
const L = (char, roman, tip_en, exKo, exRoman, exEn, name = '') => ({
  char,
  roman,
  name,
  tip_en,
  example: { ko: exKo, roman: exRoman, en: exEn },
});
const line = (speaker, ko, roman, en) => ({ speaker, ko, roman, en });
const p = (text, roman, tip_en) => ({ text, roman, tip_en });
const mc = (prompt, options, answer, ko = '') => ({ type: 'mc', prompt, ko, options, answer });
const listen = (say, options, answer, prompt = 'Listen and choose what you hear.') => ({
  type: 'listen',
  prompt,
  say,
  options,
  answer,
});
const order = (en, words) => ({ type: 'order', prompt: 'Put the words in the right order.', en, words });

export const bonusLessons = [
  {
    id: 'C1',
    unitId: 'UB',
    status: 'draft',
    order: 10,
    kind: 'standard',
    title: { ko: '안녕하세요!', en: 'Hello!' },
    objectives: ['Greet people politely', 'Say thank you, sorry and goodbye', 'Choose 안녕히 가세요 vs 안녕히 계세요'],
    warmup: { emoji: '🙇', question_en: 'In Korea, people often bow a little when they say hello. How do people greet each other in your country?' },
    vocab: [
      v('안녕하세요', 'annyeonghaseyo', 'Hello (polite)', '👋'),
      v('안녕', 'annyeong', 'Hi / Bye (to friends)', '✌️'),
      v('반가워요', 'bangawoyo', 'Nice to meet you', '🤝'),
      v('감사합니다', 'gamsahamnida', 'Thank you (formal)', '🙏'),
      v('고마워요', 'gomawoyo', 'Thanks (polite)', '😊'),
      v('죄송합니다', 'joesonghamnida', 'I’m sorry (formal)', '🙇'),
      v('미안해요', 'mianhaeyo', 'Sorry (polite)', '😅'),
      v('안녕히 가세요', 'annyeonghi gaseyo', 'Goodbye (to someone leaving)', '🚶'),
      v('안녕히 계세요', 'annyeonghi gyeseyo', 'Goodbye (to someone staying)', '🏠'),
      v('네', 'ne', 'Yes', '⭕'),
      v('아니요', 'aniyo', 'No', '❌'),
      v('내일 봐요', 'naeil bwayo', 'See you tomorrow', '📅'),
    ],
    grammar: [
      {
        pattern: 'Speech levels',
        meaning_en: 'Formal · Polite · Casual',
        explanation_en: 'Korean changes the ending depending on who you talk to. -(스)ㅂ니다 is formal (presentations, news). -아요/어요 is polite (most daily talk — use this with teachers and new people). Casual 반말 is only for close friends of the same age or younger.',
        examples: [
          { ko: '감사합니다 / 고마워요 / 고마워', en: 'formal / polite / casual “thank you”' },
          { ko: '안녕하세요 / 안녕', en: 'polite / casual “hello”' },
        ],
      },
      {
        pattern: '안녕히 가세요 vs 안녕히 계세요',
        meaning_en: 'Two ways to say goodbye',
        explanation_en: '가세요 = “go in peace” → say it to the person who is LEAVING. 계세요 = “stay in peace” → say it to the person who is STAYING when YOU leave.',
        examples: [
          { ko: '(You leave the classroom) 선생님, 안녕히 계세요!', en: 'Goodbye, teacher! (teacher stays)' },
          { ko: '(Your friend leaves your house) 안녕히 가세요!', en: 'Goodbye! (friend leaves)' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Emma, a new exchange student, meets Minjun at the school gate. Later, she leaves the classroom.',
      lines: [
        line('민준', '안녕하세요!', 'Annyeonghaseyo!', 'Hello!'),
        line('에마', '안녕하세요! 반가워요.', 'Annyeonghaseyo! Bangawoyo.', 'Hello! Nice to meet you.'),
        line('민준', '저도 반가워요.', 'Jeodo bangawoyo.', 'Nice to meet you, too.'),
        line('에마', '(after class) 안녕히 계세요!', 'Annyeonghi gyeseyo!', 'Goodbye! (I’m leaving)'),
        line('민준', '안녕히 가세요! 내일 봐요!', 'Annyeonghi gaseyo! Naeil bwayo!', 'Goodbye! See you tomorrow!'),
      ],
    },
    pronunciation: {
      focus_en: 'Nasalization: ㅂ before ㄴ becomes [ㅁ]. 감사합니다 sounds like [감사함니다].',
      items: [
        p('안녕하세요', 'annyeonghaseyo', 'The ㅎ is very soft — almost “an-nyeong-a-se-yo”.'),
        p('감사합니다', 'gamsahamnida', '합니다 → [함니다].'),
        p('죄송합니다', 'joesonghamnida', '[죄송함니다]'),
        p('반가워요', 'bangawoyo', ''),
        p('안녕히 계세요', 'annyeonghi gyeseyo', '계 often sounds like [게].'),
      ],
    },
    quiz: [
      mc('Your friend is leaving your house. What do you say?', ['안녕히 가세요', '안녕히 계세요', '죄송합니다', '반가워요'], 0),
      mc('You meet your new teacher for the first time. Best greeting?', ['안녕', '안녕하세요', '고마워', '미안해'], 1),
      listen('고마워요', ['미안해요', '고마워요', '반가워요', '아니요'], 1),
      mc('What does 죄송합니다 mean?', ['Thank you', 'Hello', 'I’m sorry', 'Goodbye'], 2),
      order('Nice to meet you, too.', ['저도', '반가워요']),
    ],
    culture: { title: 'Bowing (인사)', body_en: 'In Korea, a small bow (about 15°) with “안녕하세요” is the normal greeting for teachers, older people and new people. With close friends a wave and “안녕!” is fine. Students in Korea often bow to teachers in the hallway.' },
    chat: {
      scenario: 'First day at a Korean school. Bori is a friendly classmate. Greet each other, say nice to meet you, and say goodbye after class.',
      goal_en: 'Use 안녕하세요, 반가워요 and 안녕히 계세요/가세요.',
      starter_ko: '안녕하세요! 저는 보리예요. 반가워요!',
      vocab: ['안녕하세요', '반가워요', '고마워요', '안녕히 가세요', '안녕히 계세요'],
    },
  },
  {
    id: 'C2',
    unitId: 'UB',
    status: 'draft',
    order: 11,
    kind: 'standard',
    title: { ko: '저는 에마예요', en: 'I’m Emma' },
    objectives: ['Introduce your name, nationality and grade', 'Use N은/는 and N이에요/예요', 'Ask “What’s your name?”'],
    warmup: { emoji: '🪪', question_en: 'If you introduce yourself to a new class, what three things do you usually say?' },
    vocab: [
      v('저', 'jeo', 'I / me (polite)', '🙋'),
      v('이름', 'ireum', 'name', '📛'),
      v('학생', 'haksaeng', 'student', '🎒'),
      v('중학생', 'junghaksaeng', 'middle school student', '🧑‍🎓'),
      v('고등학생', 'godeunghaksaeng', 'high school student', '👩‍🎓'),
      v('선생님', 'seonsaengnim', 'teacher', '🧑‍🏫'),
      v('나라', 'nara', 'country', '🌍'),
      v('사람', 'saram', 'person', '🧍'),
      v('한국', 'hanguk', 'Korea', '🇰🇷'),
      v('미국', 'miguk', 'the USA', '🇺🇸'),
      v('영국', 'yeongguk', 'the UK', '🇬🇧'),
      v('호주', 'hoju', 'Australia', '🇦🇺'),
      v('캐나다', 'kaenada', 'Canada', '🇨🇦'),
    ],
    grammar: [
      {
        pattern: 'N은/는',
        meaning_en: 'Topic marker — “as for N”',
        explanation_en: 'Use 은 after a consonant (받침), 는 after a vowel.',
        examples: [
          { ko: '저는 학생이에요.', en: 'I am a student.' },
          { ko: '선생님은 한국 사람이에요.', en: 'The teacher is Korean.' },
        ],
      },
      {
        pattern: 'N이에요/예요',
        meaning_en: '“to be” — It is N / I am N',
        explanation_en: 'After a consonant → 이에요. After a vowel → 예요. Add a rising tone to make a question.',
        examples: [
          { ko: '저는 에마예요.', en: 'I am Emma. (에마 ends in a vowel)' },
          { ko: '저는 고등학생이에요.', en: 'I am a high school student. (생 ends in ㅇ)' },
          { ko: '이름이 뭐예요?', en: 'What is your name?' },
          { ko: '어느 나라 사람이에요?', en: 'Which country are you from?' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Emma meets Jia in the school library.',
      lines: [
        line('지아', '안녕하세요? 저는 박지아예요.', 'Annyeonghaseyo? Jeoneun Bak Jiayeyo.', 'Hi! I’m Park Jia.'),
        line('에마', '안녕하세요. 저는 에마예요.', 'Annyeonghaseyo. Jeoneun Emayeyo.', 'Hi. I’m Emma.'),
        line('지아', '에마 씨는 어느 나라 사람이에요?', 'Ema ssineun eoneu nara saramieyo?', 'Emma, which country are you from?'),
        line('에마', '저는 호주 사람이에요.', 'Jeoneun hoju saramieyo.', 'I’m from Australia.'),
        line('지아', '아, 그래요? 저는 고등학생이에요.', 'A, geuraeyo? Jeoneun godeunghaksaengieyo.', 'Oh, really? I’m a high school student.'),
        line('에마', '저도 고등학생이에요!', 'Jeodo godeunghaksaengieyo!', 'I’m a high school student, too!'),
      ],
    },
    pronunciation: {
      focus_en: 'Linking (연음): 사람이에요 → [사라미에요]. Tensification: 학생 → [학쌩].',
      items: [
        p('저는 학생이에요', 'jeoneun haksaengieyo', '학생 sounds like [학쌩].'),
        p('사람이에요', 'saramieyo', '[사라미에요]'),
        p('이름이 뭐예요?', 'ireumi mwoyeyo?', '[이르미]; raise your voice at the end.'),
        p('선생님', 'seonsaengnim', ''),
        p('한국 사람', 'hanguk saram', '[한국 싸람] is common in fast speech.'),
      ],
    },
    quiz: [
      mc('저는 학생___.', ['이에요', '예요', '은', '는'], 0),
      mc('저는 에마___.', ['이에요', '예요', '을', '이'], 1),
      mc('선생님___ 한국 사람이에요.', ['는', '은', '예요', '이에요'], 1),
      listen('선생님', ['선생님', '학생', '사람', '이름'], 0),
      order('I am Canadian.', ['저는', '캐나다', '사람이에요']),
    ],
    culture: { title: 'Korean names', body_en: 'Korean names put the family name first: 박지아 = family name 박 (Park) + given name 지아. The most common family names are 김 (Kim), 이 (Lee) and 박 (Park). Add 씨 after a name to be polite (에마 씨), but never use 씨 with your own name — and call teachers 선생님, not by their name.' },
    chat: {
      scenario: 'Bori is a curious new friend. Introduce yourself: your name, country, and whether you are a middle or high school student. Ask Bori questions too.',
      goal_en: 'Use 저는 ___이에요/예요 and ___ 사람이에요.',
      starter_ko: '안녕하세요! 저는 보리예요. 이름이 뭐예요?',
      vocab: ['이름', '저는', '사람이에요', '학생', '고등학생', '중학생'],
    },
  },

  {
    id: 'C3',
    unitId: 'UB',
    status: 'draft',
    order: 20,
    kind: 'standard',
    title: { ko: '이게 뭐예요?', en: 'What is this?' },
    objectives: ['Name classroom objects', 'Ask “What is this/that?”', 'Say “I have / I don’t have” with 있어요/없어요'],
    warmup: { emoji: '🎒', question_en: 'What is in your school bag right now? Try to list five things.' },
    vocab: [
      v('책', 'chaek', 'book', '📕'),
      v('공책', 'gongchaek', 'notebook', '📓'),
      v('연필', 'yeonpil', 'pencil', '✏️'),
      v('지우개', 'jiugae', 'eraser', '🧽'),
      v('필통', 'piltong', 'pencil case', '🖍️'),
      v('가방', 'gabang', 'bag', '🎒'),
      v('책상', 'chaeksang', 'desk', '🪑'),
      v('의자', 'uija', 'chair', '💺'),
      v('휴대폰', 'hyudaepon', 'cell phone', '📱'),
      v('이거 / 이게', 'igeo / ige', 'this (thing)', '👇'),
      v('그거', 'geugeo', 'that (near you)', '👉'),
      v('저거', 'jeogeo', 'that (over there)', '🫵'),
      v('있어요', 'isseoyo', 'have / there is', '✅'),
      v('없어요', 'eopseoyo', 'don’t have / there isn’t', '🚫'),
    ],
    grammar: [
      {
        pattern: '이게 / 그게 / 저게 뭐예요?',
        meaning_en: 'What is this / that?',
        explanation_en: '이 = near me, 그 = near you, 저 = far from both of us. 이게 is short for 이것이.',
        examples: [
          { ko: '이게 뭐예요? — 연필이에요.', en: 'What is this? — It’s a pencil.' },
          { ko: '저게 뭐예요? — 시계예요.', en: 'What is that over there? — It’s a clock.' },
        ],
      },
      {
        pattern: 'N이/가 있어요 / 없어요',
        meaning_en: 'I have N / I don’t have N',
        explanation_en: 'Use 이 after a consonant, 가 after a vowel.',
        examples: [
          { ko: '지우개가 있어요?', en: 'Do you have an eraser?' },
          { ko: '네, 있어요. / 아니요, 없어요.', en: 'Yes, I do. / No, I don’t.' },
          { ko: '연필이 없어요.', en: 'I don’t have a pencil.' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'In class, Emma is curious about Minjun’s cute pencil case.',
      lines: [
        line('에마', '민준 씨, 이게 뭐예요?', 'Minjun ssi, ige mwoyeyo?', 'Minjun, what is this?'),
        line('민준', '그거요? 필통이에요.', 'Geugeoyo? Piltongieyo.', 'That? It’s a pencil case.'),
        line('에마', '와, 귀여워요! 지우개 있어요?', 'Wa, gwiyeowoyo! Jiugae isseoyo?', 'Wow, cute! Do you have an eraser?'),
        line('민준', '네, 있어요. 여기요.', 'Ne, isseoyo. Yeogiyo.', 'Yes, I do. Here.'),
        line('에마', '고마워요. 그런데 연필이 없어요...', 'Gomawoyo. Geureonde yeonpiri eopseoyo...', 'Thanks. But I don’t have a pencil...'),
        line('민준', '하하, 연필도 여기 있어요!', 'Haha, yeonpildo yeogi isseoyo!', 'Haha, here’s a pencil, too!'),
      ],
    },
    pronunciation: {
      focus_en: '있어요 → [이써요], 없어요 → [업써요]. 책상 → [책쌍].',
      items: [p('있어요', 'isseoyo', '[이써요]'), p('없어요', 'eopseoyo', '[업써요]'), p('책상', 'chaeksang', '[책쌍]'), p('연필이 없어요', 'yeonpiri eopseoyo', '[연피리 업써요]'), p('이게 뭐예요?', 'ige mwoyeyo?', '')],
    },
    quiz: [
      mc('지우개___ 있어요?', ['이', '가', '은', '를'], 1),
      mc('연필___ 없어요.', ['이', '가', '는', '예요'], 0),
      listen('공책', ['공책', '책상', '필통', '가방'], 0),
      mc('Something is far from both of you. How do you ask what it is?', ['이게 뭐예요?', '그게 뭐예요?', '저게 뭐예요?'], 2),
      order('Do you have a pencil?', ['연필이', '있어요?']),
    ],
    culture: { title: 'Korean classrooms', body_en: 'In many Korean schools, students stay in one classroom and teachers move between rooms. Students clean their classroom together at the end of the day (청소 시간), and most schools have uniforms (교복).' },
    chat: {
      scenario: 'You forgot your stationery. Bori is your deskmate. Ask what things are and whether Bori has a pencil, eraser, or notebook you can borrow.',
      goal_en: 'Use 이게 뭐예요? and ___이/가 있어요?',
      starter_ko: '안녕! 아, 오늘 가방이 없어요? 뭐가 필요해요?',
      vocab: ['연필', '지우개', '공책', '필통', '있어요', '없어요'],
    },
  },
  {
    id: 'C4',
    unitId: 'UB',
    status: 'draft',
    order: 21,
    kind: 'standard',
    title: { ko: '매점이 어디에 있어요?', en: 'Where is the snack shop?' },
    objectives: ['Name places at school', 'Ask and answer “Where is ...?”', 'Use location words 앞/뒤/옆/위/아래'],
    warmup: { emoji: '🗺️', question_en: 'What is your favorite place at your school? Why?' },
    vocab: [
      v('교실', 'gyosil', 'classroom', '🏫'),
      v('화장실', 'hwajangsil', 'restroom', '🚻'),
      v('도서관', 'doseogwan', 'library', '📚'),
      v('매점', 'maejeom', 'school snack shop', '🍙'),
      v('운동장', 'undongjang', 'sports field', '⚽'),
      v('급식실', 'geupsiksil', 'school cafeteria', '🍱'),
      v('교무실', 'gyomusil', 'teachers’ office', '🗂️'),
      v('어디', 'eodi', 'where', '❓'),
      v('앞', 'ap', 'front', '⬆️'),
      v('뒤', 'dwi', 'behind', '⬇️'),
      v('옆', 'yeop', 'next to', '↔️'),
      v('위', 'wi', 'on / above', '🔼'),
      v('아래', 'arae', 'under / below', '🔽'),
    ],
    grammar: [
      {
        pattern: 'N이/가 어디에 있어요?',
        meaning_en: 'Where is N?',
        explanation_en: '에 marks location. Answer with “place + 에 있어요”.',
        examples: [
          { ko: '화장실이 어디에 있어요?', en: 'Where is the restroom?' },
          { ko: '1층에 있어요.', en: 'It’s on the first floor.' },
        ],
      },
      {
        pattern: 'N 앞/뒤/옆/위/아래에 있어요',
        meaning_en: 'It’s in front of / behind / next to / on / under N',
        explanation_en: 'Put the reference place FIRST, then the position word, then 에.',
        examples: [
          { ko: '도서관 옆에 있어요.', en: 'It’s next to the library.' },
          { ko: '가방이 책상 아래에 있어요.', en: 'The bag is under the desk.' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Emma is hungry between classes and asks Jia for directions.',
      lines: [
        line('에마', '실례합니다. 매점이 어디에 있어요?', 'Sillyehamnida. Maejeomi eodie isseoyo?', 'Excuse me. Where is the snack shop?'),
        line('지아', '매점이요? 도서관 옆에 있어요.', 'Maejeomiyo? Doseogwan yeope isseoyo.', 'The snack shop? It’s next to the library.'),
        line('에마', '도서관은 어디에 있어요?', 'Doseogwaneun eodie isseoyo?', 'And where is the library?'),
        line('지아', '운동장 앞에 있어요. 같이 가요!', 'Undongjang ape isseoyo. Gachi gayo!', 'It’s in front of the sports field. Let’s go together!'),
        line('에마', '정말요? 고마워요!', 'Jeongmallyo? Gomawoyo!', 'Really? Thank you!'),
      ],
    },
    pronunciation: {
      focus_en: 'Linking again: 옆에 → [여페], 앞에 → [아페]. 실례합니다 → [실레함니다]. 같이 → [가치]!',
      items: [p('어디에 있어요?', 'eodie isseoyo?', '[어디에 이써요]'), p('옆에', 'yeope', '[여페]'), p('앞에', 'ape', '[아페]'), p('같이 가요', 'gachi gayo', '같이 → [가치]'), p('실례합니다', 'sillyehamnida', '[실레함니다]'), p('급식실', 'geupsiksil', '[급씩씰]')],
    },
    quiz: [
      mc('Where do you go to borrow books?', ['매점', '도서관', '화장실', '운동장'], 1),
      listen('화장실', ['화장실', '교실', '급식실', '교무실'], 0),
      mc('“It’s next to the library.”', ['도서관 앞에 있어요.', '도서관 옆에 있어요.', '도서관 뒤에 있어요.', '도서관 위에 있어요.'], 1),
      mc('How is 같이 pronounced?', ['[가티]', '[가치]', '[같이]', '[가시]'], 1),
      order('Where is the restroom?', ['화장실이', '어디에', '있어요?']),
    ],
    culture: { title: '매점 & 급식', body_en: 'Korean schools serve a hot lunch (급식) — rice, soup, kimchi and side dishes — and students rate the menu every day! The 매점 (snack shop) is the most popular place during break time.' },
    chat: {
      scenario: 'You are new at a Korean school. Bori is a student guide. Ask where places are (restroom, library, snack shop, cafeteria) and Bori will explain using 앞/뒤/옆.',
      goal_en: 'Ask ___이/가 어디에 있어요? and understand the answers.',
      starter_ko: '안녕하세요! 저는 학교 안내 도우미 보리예요. 어디에 가요?',
      vocab: ['화장실', '도서관', '매점', '급식실', '어디', '옆', '앞'],
    },
  },

  {
    id: 'C5',
    unitId: 'UB',
    status: 'draft',
    order: 30,
    kind: 'standard',
    title: { ko: '우리 가족', en: 'My Family' },
    objectives: ['Name family members', 'Ask “Who is this?”', 'Understand 언니/오빠/누나/형'],
    warmup: { emoji: '📸', question_en: 'Who is in your family? Do you have brothers or sisters?' },
    vocab: [
      v('가족', 'gajok', 'family', '👨‍👩‍👧‍👦'),
      v('아버지 / 아빠', 'abeoji / appa', 'father / dad', '👨'),
      v('어머니 / 엄마', 'eomeoni / eomma', 'mother / mom', '👩'),
      v('할아버지', 'harabeoji', 'grandfather', '👴'),
      v('할머니', 'halmeoni', 'grandmother', '👵'),
      v('형', 'hyeong', 'older brother (said by a boy)', '👦'),
      v('오빠', 'oppa', 'older brother (said by a girl)', '👦'),
      v('누나', 'nuna', 'older sister (said by a boy)', '👧'),
      v('언니', 'eonni', 'older sister (said by a girl)', '👧'),
      v('남동생', 'namdongsaeng', 'younger brother', '🧒'),
      v('여동생', 'yeodongsaeng', 'younger sister', '👧'),
      v('누구', 'nugu', 'who', '❓'),
      v('우리', 'uri', 'we / our', '🫶'),
    ],
    grammar: [
      {
        pattern: 'N이/가 누구예요?',
        meaning_en: 'Who is N?',
        explanation_en: '이 사람 (this person) + 은 → 이 사람은 누구예요? To be extra polite about an older person use 이분.',
        examples: [
          { ko: '이 사람은 누구예요?', en: 'Who is this (person)?' },
          { ko: '이분은 우리 할머니예요.', en: 'This is my grandmother.' },
        ],
      },
      {
        pattern: '우리 / 제',
        meaning_en: '“our” and “my”',
        explanation_en: 'Koreans usually say 우리 (our) for family, school and country — 우리 엄마, 우리 학교 — even if they are an only child! 제 = my (polite).',
        examples: [
          { ko: '우리 언니예요.', en: 'It’s my older sister.' },
          { ko: '제 남동생이에요.', en: 'It’s my younger brother.' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Minjun looks at a family photo on Emma’s phone.',
      lines: [
        line('민준', '에마 씨, 이 사람은 누구예요?', 'Ema ssi, i sarameun nuguyeyo?', 'Emma, who is this?'),
        line('에마', '우리 언니예요. 대학생이에요.', 'Uri eonniyeyo. Daehaksaengieyo.', 'That’s my older sister. She’s a university student.'),
        line('민준', '아, 그래요? 이 남자아이는요?', 'A, geuraeyo? I namjaaineunyo?', 'Oh, really? And this boy?'),
        line('에마', '제 남동생이에요. 정말 귀여워요.', 'Je namdongsaengieyo. Jeongmal gwiyeowoyo.', 'That’s my little brother. He’s really cute.'),
        line('민준', '이분은 할머니예요?', 'Ibuneun halmeoniyeyo?', 'Is this your grandmother?'),
        line('에마', '네, 우리 할머니예요!', 'Ne, uri halmeoniyeyo!', 'Yes, that’s my grandma!'),
      ],
    },
    pronunciation: {
      focus_en: 'ㅎ is often silent between voiced sounds: 할아버지 → [하라버지].',
      items: [p('할아버지', 'harabeoji', '[하라버지]'), p('할머니', 'halmeoni', ''), p('남동생', 'namdongsaeng', ''), p('누구예요?', 'nuguyeyo?', 'Rising tone.'), p('우리 언니예요', 'uri eonniyeyo', '')],
    },
    quiz: [
      mc('A girl talks about her older sister. Which word?', ['누나', '언니', '오빠', '형'], 1),
      mc('A boy talks about his older brother. Which word?', ['형', '오빠', '누나', '남동생'], 0),
      listen('할아버지', ['할머니', '할아버지', '아버지', '어머니'], 1),
      mc('What does 누구 mean?', ['what', 'where', 'who', 'when'], 2),
      order('Who is this person?', ['이', '사람은', '누구예요?']),
    ],
    culture: { title: 'Family words for everyone', body_en: 'Koreans use family words for people who are NOT family: girls call close older girl friends 언니, boys call older boy friends 형, and in K-dramas you will hear 오빠 a lot! At a restaurant, people may call the server 이모 (aunt). It shows warmth and closeness.' },
    chat: {
      scenario: 'Show Bori a (pretend) photo of your family and introduce each person. Bori will ask questions like 이 사람은 누구예요?',
      goal_en: 'Introduce at least 3 family members.',
      starter_ko: '와, 가족 사진이에요? 이 사람은 누구예요?',
      vocab: ['가족', '엄마', '아빠', '언니', '오빠', '형', '누나', '동생'],
    },
  },
  {
    id: 'C6',
    unitId: 'UB',
    status: 'draft',
    order: 31,
    kind: 'standard',
    title: { ko: '몇 살이에요?', en: 'How old are you?' },
    objectives: ['Count 1–20 with native Korean numbers', 'Say your age with 살', 'Count people and things with 명 and 개'],
    warmup: { emoji: '🎂', question_en: 'Korean has TWO number systems! Today we learn the native Korean one: 하나, 둘, 셋...' },
    vocab: [
      v('하나', 'hana', 'one', '1️⃣'),
      v('둘', 'dul', 'two', '2️⃣'),
      v('셋', 'set', 'three', '3️⃣'),
      v('넷', 'net', 'four', '4️⃣'),
      v('다섯', 'daseot', 'five', '5️⃣'),
      v('여섯', 'yeoseot', 'six', '6️⃣'),
      v('일곱', 'ilgop', 'seven', '7️⃣'),
      v('여덟', 'yeodeol', 'eight', '8️⃣'),
      v('아홉', 'ahop', 'nine', '9️⃣'),
      v('열', 'yeol', 'ten', '🔟'),
      v('스물', 'seumul', 'twenty', '2️⃣0️⃣'),
      v('살', 'sal', 'years old (counter)', '🎂'),
      v('명', 'myeong', 'people (counter)', '🧑‍🤝‍🧑'),
      v('개', 'gae', 'things (counter)', '📦'),
      v('몇', 'myeot', 'how many', '❓'),
    ],
    grammar: [
      {
        pattern: 'Number + counter',
        meaning_en: 'Counting with native numbers',
        explanation_en: 'Before a counter, 하나→한, 둘→두, 셋→세, 넷→네, 스물→스무. 11 = 열하나 (열한 살), 15 = 열다섯.',
        examples: [
          { ko: '한 살, 두 살, 세 살, 네 살', en: '1, 2, 3, 4 years old' },
          { ko: '열여섯 살이에요.', en: 'I am 16 years old.' },
          { ko: '가족이 네 명이에요.', en: 'There are four people in my family.' },
          { ko: '사과 두 개 있어요.', en: 'I have two apples.' },
        ],
      },
      {
        pattern: '몇 + counter',
        meaning_en: 'How many ...?',
        explanation_en: '몇 살이에요? (How old?) 몇 명이에요? (How many people?) 몇 개예요? (How many things?)',
        examples: [
          { ko: '몇 살이에요?', en: 'How old are you?' },
          { ko: '가족이 몇 명이에요?', en: 'How many people are in your family?' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Jia and Emma find out they are the same age.',
      lines: [
        line('지아', '에마 씨, 몇 살이에요?', 'Ema ssi, myeot sarieyo?', 'Emma, how old are you?'),
        line('에마', '저는 열여섯 살이에요. 지아 씨는요?', 'Jeoneun yeollyeoseot sarieyo. Jia ssineunyo?', 'I’m sixteen. And you, Jia?'),
        line('지아', '저도 열여섯 살이에요! 우리 동갑이에요.', 'Jeodo yeollyeoseot sarieyo! Uri donggabieyo.', 'I’m sixteen too! We’re the same age.'),
        line('에마', '와! 가족은 몇 명이에요?', 'Wa! Gajogeun myeot myeongieyo?', 'Wow! How many people are in your family?'),
        line('지아', '네 명이에요. 에마 씨는요?', 'Ne myeongieyo. Ema ssineunyo?', 'Four. What about you?'),
        line('에마', '우리 가족은 다섯 명이에요.', 'Uri gajogeun daseot myeongieyo.', 'There are five people in my family.'),
      ],
    },
    pronunciation: {
      focus_en: 'Watch out: 열여섯 → [열려섣], 몇 살 → [멷쌀], 여덟 → [여덜].',
      items: [p('하나 둘 셋 넷 다섯', 'hana dul set net daseot', 'Count with rhythm!'), p('여섯 일곱 여덟 아홉 열', 'yeoseot ilgop yeodeol ahop yeol', '여덟 → [여덜]'), p('몇 살이에요?', 'myeot sarieyo?', '[멷 싸리에요]'), p('열여섯 살', 'yeollyeoseot sal', '[열려섣 쌀]'), p('네 명이에요', 'ne myeongieyo', '')],
    },
    quiz: [
      mc('How do you say “3 years old”?', ['셋 살', '세 살', '삼 살', '세 개'], 1),
      listen('일곱', ['여덟', '일곱', '아홉', '여섯'], 1),
      mc('열다섯 = ?', ['13', '14', '15', '50'], 2),
      mc('Which counter is used for people?', ['개', '살', '명', '권'], 2),
      order('How old are you?', ['몇', '살이에요?']),
    ],
    culture: { title: 'Age and 동갑', body_en: 'Age matters in Korea because it decides how you talk to someone. People the same age (동갑) can quickly become friends and switch to casual speech (반말). Since 2023, Korea officially uses “international age” in law, but you will still hear people talk about “Korean age” in dramas!' },
    chat: {
      scenario: 'Chat with Bori about ages and family: how old you are, how many people are in your family, and how many pets or things you have.',
      goal_en: 'Use native numbers with 살, 명 and 개.',
      starter_ko: '저는 열다섯 살이에요. 몇 살이에요?',
      vocab: ['몇', '살', '명', '개', '하나', '둘', '셋', '넷', '다섯'],
    },
  },

  {
    id: 'C7',
    unitId: 'UB',
    status: 'draft',
    order: 40,
    kind: 'standard',
    title: { ko: '주말에 뭐 해요?', en: 'What do you do on weekends?' },
    objectives: ['Conjugate verbs in the polite present tense (-아요/어요)', 'Use the object marker 을/를', 'Talk about weekend activities'],
    warmup: { emoji: '🎮', question_en: 'What did you do last weekend? Movies, sports, games, K-pop?' },
    vocab: [
      v('가다 → 가요', 'gada → gayo', 'to go', '🚶'),
      v('오다 → 와요', 'oda → wayo', 'to come', '🏃'),
      v('먹다 → 먹어요', 'meokda → meogeoyo', 'to eat', '🍜'),
      v('마시다 → 마셔요', 'masida → masyeoyo', 'to drink', '🧋'),
      v('보다 → 봐요', 'boda → bwayo', 'to watch / see', '📺'),
      v('만나다 → 만나요', 'mannada → mannayo', 'to meet', '🤝'),
      v('듣다 → 들어요', 'deutda → deureoyo', 'to listen', '🎧'),
      v('공부하다 → 공부해요', 'gongbuhada → gongbuhaeyo', 'to study', '📖'),
      v('운동하다 → 운동해요', 'undonghada → undonghaeyo', 'to exercise', '🏀'),
      v('주말', 'jumal', 'weekend', '📅'),
      v('친구', 'chingu', 'friend', '🧑‍🤝‍🧑'),
      v('영화', 'yeonghwa', 'movie', '🎬'),
      v('음악', 'eumak', 'music', '🎵'),
    ],
    grammar: [
      {
        pattern: 'V-아요 / 어요 / 해요',
        meaning_en: 'Polite present tense',
        explanation_en: 'Remove 다. If the last vowel is ㅏ or ㅗ → add 아요. Otherwise → add 어요. 하다 → 해요. Vowels often merge: 가+아요 = 가요, 보+아요 = 봐요, 마시+어요 = 마셔요. 듣다 is irregular: 들어요.',
        examples: [
          { ko: '살다 → 살아요 / 먹다 → 먹어요', en: 'live / eat' },
          { ko: '보다 → 봐요 / 마시다 → 마셔요', en: 'watch / drink (merged vowels)' },
          { ko: '공부하다 → 공부해요', en: 'study' },
        ],
      },
      {
        pattern: 'N을/를 + V',
        meaning_en: 'Object marker',
        explanation_en: '을 after a consonant, 를 after a vowel. Word order: Subject – Object – Verb.',
        examples: [
          { ko: '영화를 봐요.', en: 'I watch a movie.' },
          { ko: '음악을 들어요.', en: 'I listen to music.' },
          { ko: '주말에 친구를 만나요.', en: 'I meet friends on the weekend.' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'Friday afternoon. Minjun asks Emma about her weekend plans.',
      lines: [
        line('민준', '에마 씨, 주말에 뭐 해요?', 'Ema ssi, jumare mwo haeyo?', 'Emma, what do you do on the weekend?'),
        line('에마', '친구를 만나요. 같이 영화를 봐요.', 'Chingureul mannayo. Gachi yeonghwareul bwayo.', 'I meet a friend. We watch a movie together.'),
        line('민준', '무슨 영화를 봐요?', 'Museun yeonghwareul bwayo?', 'What movie?'),
        line('에마', '한국 영화를 봐요. 민준 씨는요?', 'Hanguk yeonghwareul bwayo. Minjun ssineunyo?', 'A Korean movie. How about you, Minjun?'),
        line('민준', '저는 운동해요. 그리고 음악을 들어요.', 'Jeoneun undonghaeyo. Geurigo eumageul deureoyo.', 'I exercise. And I listen to music.'),
      ],
    },
    pronunciation: {
      focus_en: 'Linking with 을: 음악을 → [으마글], 먹어요 → [머거요].',
      items: [p('먹어요', 'meogeoyo', '[머거요]'), p('음악을 들어요', 'eumageul deureoyo', '[으마글 드러요]'), p('주말에 뭐 해요?', 'jumare mwo haeyo?', '[주마레]'), p('영화를 봐요', 'yeonghwareul bwayo', ''), p('공부해요', 'gongbuhaeyo', '')],
    },
    quiz: [
      mc('먹다 → ?', ['먹아요', '먹어요', '먹해요', '머요'], 1),
      mc('보다 → ?', ['보어요', '봐요', '보요', '버요'], 1),
      mc('영화___ 봐요.', ['을', '를', '이', '은'], 1),
      listen('공부해요', ['운동해요', '공부해요', '공부했어요', '좋아해요'], 1),
      order('I listen to music.', ['음악을', '들어요']),
    ],
    culture: { title: 'Weekends for Korean teens', body_en: 'Many Korean high school students go to 학원 (private academies) even on weekends! In free time, popular activities are 노래방 (karaoke), PC방 (internet cafés), photo booths (인생네컷) and hanging out at cafés.' },
    chat: {
      scenario: 'It’s Friday. Talk with Bori about what you do on weekends. Bori will ask follow-up questions.',
      goal_en: 'Use at least 3 verbs in -아요/어요 form with 을/를.',
      starter_ko: '내일 주말이에요! 주말에 보통 뭐 해요?',
      vocab: ['주말', '친구', '영화', '음악', '만나요', '봐요', '들어요', '먹어요'],
    },
  },
  {
    id: 'C8',
    unitId: 'UB',
    status: 'draft',
    order: 41,
    kind: 'standard',
    title: { ko: '떡볶이 주세요!', en: 'Tteokbokki, please!' },
    objectives: ['Order food politely with 주세요', 'Ask for the price', 'Use Sino-Korean numbers for money (원)'],
    warmup: { emoji: '🍢', question_en: 'Have you ever tried Korean food? Which dish would you like to try first?' },
    vocab: [
      v('떡볶이', 'tteokbokki', 'spicy rice cakes', '🍢'),
      v('김밥', 'gimbap', 'seaweed rice roll', '🍙'),
      v('라면', 'ramyeon', 'instant noodles', '🍜'),
      v('물', 'mul', 'water', '💧'),
      v('주세요', 'juseyo', 'please give me', '🙏'),
      v('얼마예요?', 'eolmayeyo?', 'how much is it?', '💰'),
      v('원', 'won', 'won (Korean money)', '₩'),
      v('천', 'cheon', 'thousand', '🔢'),
      v('만', 'man', 'ten thousand', '🔢'),
      v('맛있어요', 'masisseoyo', 'it’s delicious', '😋'),
      v('매워요', 'maewoyo', 'it’s spicy', '🌶️'),
      v('줄', 'jul', 'counter for gimbap rolls', '➖'),
    ],
    grammar: [
      {
        pattern: 'N (number + counter) 주세요',
        meaning_en: 'Please give me N',
        explanation_en: 'The most useful phrase for shopping and ordering. Use 하고 to say “and”.',
        examples: [
          { ko: '물 주세요.', en: 'Water, please.' },
          { ko: '떡볶이 하나 주세요.', en: 'One tteokbokki, please.' },
          { ko: '떡볶이하고 김밥 두 줄 주세요.', en: 'Tteokbokki and two rolls of gimbap, please.' },
        ],
      },
      {
        pattern: 'Sino-Korean numbers & money',
        meaning_en: '일, 이, 삼 ... + 원',
        explanation_en: 'Money uses Sino-Korean numbers: 일 이 삼 사 오 육 칠 팔 구 십, 백(100), 천(1,000), 만(10,000). 3,500원 = 삼천오백 원. 12,000원 = 만 이천 원 (not 일만!).',
        examples: [
          { ko: '얼마예요? — 오천 원이에요.', en: 'How much? — It’s 5,000 won.' },
          { ko: '모두 만 이천 원이에요.', en: 'It’s 12,000 won in total.' },
        ],
      },
    ],
    dialogue: {
      setting_en: 'After school, Jia takes Emma to a 분식집 (snack restaurant).',
      lines: [
        line('사장님', '어서 오세요!', 'Eoseo oseyo!', 'Welcome!'),
        line('지아', '떡볶이 하나하고 김밥 두 줄 주세요.', 'Tteokbokki hanahago gimbap du jul juseyo.', 'One tteokbokki and two rolls of gimbap, please.'),
        line('사장님', '네, 모두 만 이천 원이에요.', 'Ne, modu man icheon wonieyo.', 'OK, that’s 12,000 won in total.'),
        line('에마', '와, 떡볶이 진짜 맛있어요!', 'Wa, tteokbokki jinjja masisseoyo!', 'Wow, the tteokbokki is really good!'),
        line('지아', '안 매워요?', 'An maewoyo?', 'Isn’t it spicy?'),
        line('에마', '조금 매워요. 그래도 맛있어요!', 'Jogeum maewoyo. Geuraedo masisseoyo!', 'A little spicy. But it’s delicious!'),
      ],
    },
    pronunciation: {
      focus_en: 'Tense sounds appear in food words: 떡볶이 → [떡뽀끼], 김밥 → [김빱]. 맛있어요 → [마시써요].',
      items: [p('떡볶이', 'tteokbokki', '[떡뽀끼] — three tense sounds!'), p('김밥', 'gimbap', '[김빱]'), p('맛있어요', 'masisseoyo', '[마시써요]'), p('얼마예요?', 'eolmayeyo?', ''), p('물 주세요', 'mul juseyo', ''), p('만 이천 원', 'man icheon won', '')],
    },
    quiz: [
      mc('How do you say 5,000 won?', ['다섯 천 원', '오천 원', '오만 원', '다섯 원'], 1),
      mc('How do you ask the price?', ['뭐예요?', '어디에 있어요?', '얼마예요?', '누구예요?'], 2),
      listen('맛있어요', ['매워요', '맛있어요', '맛없어요', '있어요'], 1),
      mc('10,000 won = ?', ['일만 원', '만 원', '십천 원', '천 원'], 1),
      order('Water, please.', ['물', '주세요']),
    ],
    culture: { title: '분식 (Korean street snacks)', body_en: '분식 restaurants serve cheap, fast snacks like 떡볶이, 김밥, 라면 and 순대. They are a favorite after-school spot for Korean students — and appear in many K-dramas! Call the owner 사장님 (boss) or 이모.' },
    chat: {
      scenario: 'Bori runs a small 분식집. Order some food and drinks, ask the price, and comment on the taste.',
      goal_en: 'Use ___ 주세요, 얼마예요? and 맛있어요.',
      starter_ko: '어서 오세요! 뭐 드릴까요?',
      vocab: ['떡볶이', '김밥', '라면', '주세요', '얼마예요', '원', '맛있어요', '매워요'],
    },
  },
];
