// Han Tutor seed curriculum, aligned with the table of contents of the introductory
// Hangeul textbook the school uses (예비편 + 12과, with a practice-application review
// after every two lessons). Only the sequence and teaching flow follow the textbook;
// every example word, explanation, dialogue and quiz item here is written for this app.
//
// Teaching flow per lesson (same as the textbook):
//   도입 warm-up → 학습 letters (mouth shape) → 쓰기 writing → 어휘 reading words
//   → 발음 listen & repeat / sound comparison → 평가 listen & choose → 과제 writing task
// Teachers can edit everything in Admin > 학습 콘텐츠.
import { bonusLessons } from './bonus.js';

const v = (ko, roman, en, emoji = '', pron = '') => ({ ko, roman, en, emoji, ...(pron ? { pron } : {}) });
const L = (char, roman, tip_en, exKo, exRoman, exEn, name = '') => ({
  char,
  roman,
  name,
  tip_en,
  example: { ko: exKo, roman: exRoman, en: exEn },
});
const line = (speaker, ko, roman, en) => ({ speaker, ko, roman, en });
const p = (text, roman, tip_en = '') => ({ text, roman, tip_en });
const w = (text, roman = '', en = '') => ({ text, roman, en });
const mc = (prompt, options, answer, ko = '') => ({ type: 'mc', prompt, ko, options, answer });
const listen = (say, options, answer, prompt = 'Listen and choose what you hear.') => ({ type: 'listen', prompt, say, options, answer });
const order = (en, words) => ({ type: 'order', prompt: 'Put the words in the right order.', en, words });
const g = (pattern, meaning_en, explanation_en, examples) => ({ pattern, meaning_en, explanation_en, examples: examples.map(([ko, en]) => ({ ko, en })) });

export const seedUnits = [
  { id: 'U0', order: 0, title: { ko: '예비편', en: 'Getting Started' }, emoji: '🇰🇷', description_en: 'Korea, the Korean language and how Hangeul was made.' },
  { id: 'U1', order: 1, title: { ko: '기본 모음과 자음', en: 'Basic Vowels & Consonants' }, emoji: '🔤', description_en: 'Lessons 1–2 and Practice 1.' },
  { id: 'U2', order: 2, title: { ko: '격음과 경음', en: 'Aspirated & Tense Sounds' }, emoji: '💨', description_en: 'Lessons 3–4 and Practice 2.' },
  { id: 'U3', order: 3, title: { ko: '이중 모음', en: 'Compound Vowels' }, emoji: '🧩', description_en: 'Lessons 5–6 and Practice 3.' },
  { id: 'U4', order: 4, title: { ko: '받침', en: 'Final Consonants' }, emoji: '🧱', description_en: 'Lessons 7–8 and Practice 4.' },
  { id: 'U5', order: 5, title: { ko: '겹받침과 연음', en: 'Double Finals & Linking' }, emoji: '🔗', description_en: 'Lessons 9–10 and Practice 5.' },
  { id: 'U6', order: 6, title: { ko: '교실 표현과 인사', en: 'Classroom & Greetings' }, emoji: '👋', description_en: 'Lessons 11–12: phrases you use every day.' },
  { id: 'UB', order: 9, title: { ko: '보너스 회화', en: 'Bonus Conversations' }, emoji: '⭐', description_en: 'Extra conversation lessons after the Hangeul course.' },
];

const lessons = [
  // ───────────── 예비편 ─────────────
  {
    id: 'L00',
    unitId: 'U0',
    order: 0,
    kind: 'hangeul',
    title: { ko: '한국어와 한글', en: 'Korean and Hangeul' },
    objectives: ['Know a few symbols of Korean culture: hanbok, hansik, hanok', 'Understand why and how King Sejong created Hangeul', 'Understand the design principles of vowels and consonants'],
    warmup: { emoji: '👑', question_en: 'Before 1443, most Koreans could not read or write, because writing used difficult Chinese characters. What would you do if you were king?' },
    letters: [
      L('·', 'sky', 'A round dot for the round sky. (Today it lives on as the short stroke in ㅏ, ㅓ, ㅗ, ㅜ.)', '하늘', 'haneul', 'sky', '천 (heaven)'),
      L('ㅡ', 'earth', 'A flat line for the flat earth.', '땅', 'ttang', 'ground', '지 (earth)'),
      L('ㅣ', 'person', 'A standing line for a person standing up.', '사람', 'saram', 'person', '인 (human)'),
      L('ㄱ', 'g/k', 'The back of the tongue rises and blocks the throat — look at the shape from the side.', '가', 'ga', '', '혀뿌리 (tongue root)'),
      L('ㄴ', 'n', 'The tongue tip touches the gum ridge behind the upper teeth.', '나', 'na', '', '혀끝 (tongue tip)'),
      L('ㅁ', 'm', 'The square shows the closed lips.', '마', 'ma', '', '입술 (lips)'),
      L('ㅅ', 's', 'Shaped like a tooth — air hisses past the teeth.', '사', 'sa', '', '이 (teeth)'),
      L('ㅇ', 'ng', 'The round throat.', '아', 'a', '', '목구멍 (throat)'),
    ],
    vocab: [
      v('한국', 'hanguk', 'Korea', '🇰🇷'),
      v('한국어', 'hangugeo', 'the Korean language', '🗣️', '[한구거]'),
      v('한글', 'hangeul', 'the Korean alphabet', '🔤'),
      v('한복', 'hanbok', 'traditional Korean clothes', '👘'),
      v('한식', 'hansik', 'Korean food', '🍲'),
      v('한옥', 'hanok', 'traditional Korean house', '🏯', '[하녹]'),
      v('세종대왕', 'sejongdaewang', 'King Sejong the Great', '👑'),
      v('훈민정음', 'hunminjeongeum', '“the correct sounds to teach the people” — Hangeul’s original name', '📜'),
    ],
    grammar: [
      g('Vowels = sky · earth · person', 'Three basic shapes make every vowel', 'Combine the three basic shapes and you get the vowels. Put the sky dot to the right of the person and you get ㅏ; under the earth line and you get ㅜ.', [
        ['ㅣ + · = ㅏ', 'person + sky (right)'],
        ['· + ㅣ = ㅓ', 'sky (left) + person'],
        ['· + ㅡ = ㅗ', 'sky above earth'],
        ['ㅡ + · = ㅜ', 'sky below earth'],
      ]),
      g('Consonants = mouth shapes + strokes', 'Five basic consonants, then add strokes', 'The five basic consonants copy the speech organs. Adding a stroke makes a stronger sound from the same place.', [
        ['ㄱ → ㅋ', 'tongue root'],
        ['ㄴ → ㄷ → ㅌ', 'tongue tip'],
        ['ㅁ → ㅂ → ㅍ', 'lips'],
        ['ㅅ → ㅈ → ㅊ', 'teeth'],
        ['ㅇ → ㅎ', 'throat'],
      ]),
    ],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Listen to these first Korean words. Many begin with 한 (han), meaning “Korean”.',
      items: [p('한국', 'hanguk'), p('한국어', 'hangugeo', '[한구거] — the ㄱ slides into 어.'), p('한글', 'hangeul'), p('한복', 'hanbok'), p('한식', 'hansik'), p('한옥', 'hanok', '[하녹]')],
    },
    quiz: [
      mc('Which one is written in Hangeul?', ['Hello', '안녕하세요', '你好', 'Bonjour'], 1),
      mc('Who created Hangeul?', ['King Sejong the Great', 'Admiral Yi Sun-sin', 'Kim Gu', 'Shin Saimdang'], 0),
      mc('Which basic shape stands for the SKY?', ['·', 'ㅡ', 'ㅣ'], 0),
      mc('ㅁ copies the shape of…', ['the throat', 'the lips', 'the teeth', 'the tongue tip'], 1),
      mc('Which one is Korean food (한식)?', ['🍕 pizza', '🍣 sushi', '🍲 bibimbap', '🌮 taco'], 2),
      mc('What is 한옥?', ['Korean clothes', 'a traditional Korean house', 'Korean food', 'the Korean alphabet'], 1),
    ],
    writing: { tip_en: 'Korean is written left to right and top to bottom. Trace the guide letters.', items: [w('한', 'han', 'Korean'), w('글', 'geul', 'writing'), w('한글', 'hangeul', 'Hangeul')] },
    culture: { title: 'Hangeul Day (한글날)', body_en: 'King Sejong finished the new alphabet in 1443 and announced it in 1446 in a book called 훈민정음 (Hunminjeongeum). Korea celebrates Hangeul Day every year on October 9. The alphabet is so logical that many people can learn to read it in a few days.' },
    chat: null,
  },

  // ───────────── 1과 기본 모음 ─────────────
  {
    id: 'L01',
    unitId: 'U1',
    order: 10,
    kind: 'hangeul',
    title: { ko: '기본 모음', en: 'Basic Vowels' },
    objectives: ['Hear and say the basic vowels ㅏ ㅓ ㅗ ㅜ ㅡ ㅣ ㅔ ㅐ', 'Build syllables with the silent ㅇ', 'Tell similar vowels apart (ㅓ/ㅗ, ㅜ/ㅡ)'],
    warmup: { emoji: '🚇', question_en: 'Look at any Korean sign or K-pop album cover. Can you find letters shaped like ㅏ, ㅗ or ㅣ?' },
    letters: [
      L('ㅏ', 'a', 'Open your mouth wide, as in “father”.', '아이', 'ai', 'child'),
      L('ㅓ', 'eo', 'Drop the jaw, lips relaxed and NOT round — like the “u” in “up”, but deeper.', '어', 'eo', 'uh? (sound)'),
      L('ㅗ', 'o', 'Round your lips into a small circle. Keep it pure — no “w” at the end.', '오', 'o', 'five'),
      L('ㅜ', 'u', 'Round your lips and push them forward, as in “moon”.', '아우', 'au', 'younger sibling'),
      L('ㅡ', 'eu', 'Lips flat and spread, teeth almost closed, tongue pulled back. No rounding!', '으', 'eu', '(the sound itself)'),
      L('ㅣ', 'i', 'Smile: “ee” as in “see”.', '이', 'i', 'two / tooth'),
      L('ㅔ', 'e', 'Like “e” in “bed”.', '에이', 'ei', 'the letter A'),
      L('ㅐ', 'ae', 'Almost the same as ㅔ in modern Korean; the mouth opens a little more.', '애', 'ae', 'kid (casual)'),
    ],
    vocab: [v('아이', 'ai', 'child', '🧒'), v('오이', 'oi', 'cucumber', '🥒'), v('아우', 'au', 'younger sibling', '👦'), v('이', 'i', 'two / tooth', '🦷'), v('오', 'o', 'five', '5️⃣'), v('에이', 'ei', 'the letter A', '🅰️'), v('애', 'ae', 'kid (casual)', '👶')],
    grammar: [
      g('ㅇ + vowel', 'Every syllable starts with a consonant', 'A vowel can’t stand alone in a syllable. When there is no consonant sound, put the silent ㅇ in front.', [
        ['ㅇ + ㅏ = 아', 'a'],
        ['ㅇ + ㅗ = 오', 'o'],
      ]),
      g('Vertical vs horizontal vowels', 'Where the vowel goes', 'Tall vowels (ㅏ ㅓ ㅣ ㅔ ㅐ) go to the RIGHT of ㅇ. Flat vowels (ㅗ ㅜ ㅡ) go UNDER it.', [
        ['아 어 이 에 애', 'vowel on the right'],
        ['오 우 으', 'vowel underneath'],
      ]),
    ],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Watch Bori’s mouth: ㅗ and ㅜ are ROUND, ㅓ and ㅡ are NOT. Then compare the pairs.',
      items: [p('아', 'a', 'Wide open.'), p('어', 'eo', 'Open, relaxed, not round.'), p('오', 'o', 'Small round lips.'), p('우', 'u', 'Lips pushed forward.'), p('으', 'eu', 'Flat lips.'), p('이', 'i', 'Big smile.'), p('에', 'e'), p('애', 'ae', 'Sounds like 에.'), p('어 오', 'eo o', 'Compare: not round → round.'), p('우 으', 'u eu', 'Compare: round → flat.'), p('아이', 'ai'), p('오이', 'oi')],
    },
    quiz: [
      listen('아', ['아', '오'], 0),
      listen('우', ['우', '아'], 0),
      listen('어', ['어', '오', '우', '으'], 0),
      listen('으', ['이', '으', '우'], 1),
      mc('ㅇ + ㅗ = ?', ['아', '오', '우', '어'], 1),
      mc('ㅇ + ㅡ = ?', ['이', '으', '우', '에'], 1),
      mc('Which vowel needs ROUND lips?', ['ㅏ', 'ㅓ', 'ㅜ', 'ㅡ'], 2),
      listen('오이', ['아이', '오이', '아우'], 1),
    ],
    writing: {
      tip_en: 'Stroke order: top to bottom, left to right. For ㅏ draw the long line first, then the short stroke.',
      items: [w('ㅏ', 'a'), w('ㅓ', 'eo'), w('ㅗ', 'o'), w('ㅜ', 'u'), w('ㅡ', 'eu'), w('ㅣ', 'i'), w('ㅔ', 'e'), w('ㅐ', 'ae'), w('아', 'a'), w('오', 'o'), w('아이', 'ai', 'child'), w('오이', 'oi', 'cucumber')],
    },
    culture: { title: 'Hangeul all around you', body_en: 'In Seoul, subway signs, bus stops and shop names are written in Hangeul, often with English underneath. Reading signs is a great way to practice — try sounding out every sign you see in a K-drama!' },
    chat: null,
  },

  // ───────────── 2과 기본 자음 ─────────────
  {
    id: 'L02',
    unitId: 'U1',
    order: 11,
    kind: 'hangeul',
    title: { ko: '기본 자음', en: 'Basic Consonants' },
    objectives: ['Hear and say the plain consonants ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅅ ㅇ ㅈ', 'Combine consonants and vowels into syllables', 'Read simple words'],
    warmup: { emoji: '🗺️', question_en: 'You already know ㄱ ㄴ ㅁ ㅅ ㅇ from the shapes of the mouth. Can you guess which sound each one makes?' },
    letters: [
      L('ㄱ', 'g/k', 'Soft “g” between vowels; close to “k” at the start of a word.', '고기', 'gogi', 'meat', '기역'),
      L('ㄴ', 'n', 'Like “n”.', '누나', 'nuna', 'older sister (said by a boy)', '니은'),
      L('ㄷ', 'd/t', 'Soft “d”; close to “t” at the start of a word.', '다리', 'dari', 'leg / bridge', '디귿'),
      L('ㄹ', 'r/l', 'A quick tap of the tongue tip — lighter than English “r”.', '우리', 'uri', 'we / our', '리을'),
      L('ㅁ', 'm', 'Close the lips: “m”.', '모자', 'moja', 'hat', '미음'),
      L('ㅂ', 'b/p', 'Soft “b”; close to “p” at the start of a word.', '바지', 'baji', 'pants', '비읍'),
      L('ㅅ', 's', '“s”. Before ㅣ it sounds like “sh”: 시 [shi].', '사자', 'saja', 'lion', '시옷'),
      L('ㅇ', '– (silent)', 'Silent at the start of a syllable.', '오리', 'ori', 'duck', '이응'),
      L('ㅈ', 'j', 'Like “j” in “jam”, but softer.', '지도', 'jido', 'map', '지읒'),
    ],
    vocab: [v('고기', 'gogi', 'meat', '🍖'), v('누나', 'nuna', 'older sister (boy speaking)', '👧'), v('다리', 'dari', 'leg / bridge', '🦵'), v('우리', 'uri', 'we / our', '🧑‍🤝‍🧑'), v('모자', 'moja', 'hat', '🧢'), v('바지', 'baji', 'pants', '👖'), v('사자', 'saja', 'lion', '🦁'), v('오리', 'ori', 'duck', '🦆'), v('지도', 'jido', 'map', '🗺️'), v('나무', 'namu', 'tree', '🌳'), v('바다', 'bada', 'sea', '🌊'), v('가수', 'gasu', 'singer', '🎤')],
    grammar: [
      g('Consonant + vowel', 'Building a syllable', 'Put the consonant in the ㅇ position. Tall vowels go to the right, flat vowels go underneath.', [
        ['ㄱ + ㅏ = 가', 'ga'],
        ['ㄴ + ㅗ = 노', 'no'],
        ['ㅁ + ㅜ = 무', 'mu'],
      ]),
      g('Sounds that change by position', 'ㄱ ㄷ ㅂ ㅈ are softer in the middle', 'At the start of a word these sound close to k / t / p / ch. Between vowels they become g / d / b / j: 고기 [ko-gi], 바다 [pa-da].', [
        ['고기', 'k at the start, g in the middle'],
        ['바다', 'p at the start, d in the middle'],
      ]),
    ],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'ㄹ is a light tap. Try 라라라 quickly! And remember 시 sounds like “shi”.',
      items: [p('가 나 다 라', 'ga na da ra'), p('마 바 사 아 자', 'ma ba sa a ja'), p('라', 'ra', 'Light tongue tap.'), p('시', 'si', 'Sounds like “shi”.'), p('고기', 'gogi'), p('나무', 'namu'), p('바다', 'bada'), p('우리', 'uri'), p('모자', 'moja'), p('지도', 'jido')],
    },
    quiz: [
      listen('나', ['나', '다'], 0),
      listen('바', ['마', '바'], 1),
      listen('라', ['나', '라', '다'], 1),
      mc('ㅈ + ㅣ = ?', ['자', '지', '주', '저'], 1),
      mc('ㅁ + ㅗ = ?', ['마', '모', '무', '머'], 1),
      listen('나무', ['나무', '다무', '마무'], 0),
      listen('바지', ['바다', '바지', '사자'], 1),
      mc('Which word means “map”?', ['지도', '모자', '다리', '우리'], 0),
    ],
    writing: {
      tip_en: 'Draw consonants top to bottom, left to right. ㄹ is three strokes: ㄱ shape, middle line, then ㄴ shape.',
      items: [w('ㄱ', 'g'), w('ㄴ', 'n'), w('ㄷ', 'd'), w('ㄹ', 'r'), w('ㅁ', 'm'), w('ㅂ', 'b'), w('ㅅ', 's'), w('ㅈ', 'j'), w('가', 'ga'), w('나', 'na'), w('고기', 'gogi', 'meat'), w('나무', 'namu', 'tree'), w('바지', 'baji', 'pants')],
    },
    culture: { title: 'Letter names', body_en: 'Each consonant has a name that shows its sound at the start and at the end of a syllable: 기역, 니은, 디귿, 리을… Korean kids learn the order ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅅ ㅇ ㅈ like the ABC song.' },
    chat: null,
  },

  // ───────────── 연습 활용 (1) ─────────────
  {
    id: 'R1',
    unitId: 'U1',
    order: 12,
    kind: 'hangeul',
    title: { ko: '연습 활용 (1)', en: 'Practice 1: Vowels & Basic Consonants' },
    objectives: ['Review basic vowels and consonants', 'Read and write two-syllable words', 'Listen and pick the right word'],
    warmup: { emoji: '🎯', question_en: 'Review time! How many Korean words can you already read? Try: 나무, 바다, 오이.' },
    vocab: [v('거미', 'geomi', 'spider', '🕷️'), v('구두', 'gudu', 'dress shoes', '👞'), v('기자', 'gija', 'reporter', '🎙️'), v('두부', 'dubu', 'tofu', '🧈'), v('머리', 'meori', 'head / hair', '💇'), v('부모', 'bumo', 'parents', '👨‍👩‍👧'), v('소리', 'sori', 'sound', '🔊'), v('어머니', 'eomeoni', 'mother', '👩'), v('이마', 'ima', 'forehead', '🙂'), v('자두', 'jadu', 'plum', '🍑')],
    grammar: [],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: { focus_en: 'Read each word smoothly, then check with the coach.', items: [p('거미', 'geomi'), p('구두', 'gudu'), p('두부', 'dubu'), p('머리', 'meori'), p('부모', 'bumo'), p('소리', 'sori'), p('어머니', 'eomeoni'), p('자두', 'jadu')] },
    quiz: [
      listen('거미', ['거미', '고미'], 0),
      listen('두부', ['도부', '두부'], 1),
      listen('머리', ['머리', '모리'], 0),
      listen('부모', ['부모', '보모'], 0),
      mc('Fill in the blank: 소_ (sound)', ['리', '나', '자', '우'], 0),
      mc('Fill in the blank: 어머_ (mother)', ['니', '리', '디', '미'], 0),
      mc('🍑 = ?', ['자두', '두부', '구두', '기자'], 0),
      mc('Which syllable has ㅂ + ㅜ?', ['보', '부', '바', '버'], 1),
    ],
    writing: { tip_en: 'Write each word in one row of boxes, one syllable per box.', items: [w('거미', 'geomi', 'spider'), w('두부', 'dubu', 'tofu'), w('머리', 'meori', 'head'), w('소리', 'sori', 'sound'), w('어머니', 'eomeoni', 'mother')] },
    culture: null,
    chat: null,
  },

  // ───────────── 3과 격음 ─────────────
  {
    id: 'L03',
    unitId: 'U2',
    order: 20,
    kind: 'hangeul',
    title: { ko: '격음', en: 'Aspirated Consonants' },
    objectives: ['Hear and say ㅋ ㅌ ㅍ ㅊ ㅎ', 'Feel the puff of air in aspirated sounds', 'Tell plain and aspirated sounds apart (가/카, 다/타, 바/파, 자/차)'],
    warmup: { emoji: '📄', question_en: 'Hold a tissue in front of your mouth and say “pa!” strongly. Does it move? That puff of air is what this lesson is about.' },
    letters: [
      L('ㅋ', 'k', 'ㄱ + a stroke = a strong k with a puff of air.', '카드', 'kadeu', 'card', '키읔'),
      L('ㅌ', 't', 'ㄷ + a stroke = a strong t with air.', '타조', 'tajo', 'ostrich', '티읕'),
      L('ㅍ', 'p', 'A strong p with air.', '파도', 'pado', 'wave', '피읖'),
      L('ㅊ', 'ch', 'ㅈ + a stroke = “ch” with air.', '치즈', 'chijeu', 'cheese', '치읓'),
      L('ㅎ', 'h', 'Air from the throat: “h”.', '하루', 'haru', 'one day', '히읗'),
    ],
    vocab: [v('카드', 'kadeu', 'card', '💳'), v('쿠키', 'kuki', 'cookie', '🍪'), v('타조', 'tajo', 'ostrich', '🦤'), v('파도', 'pado', 'wave', '🌊'), v('치즈', 'chijeu', 'cheese', '🧀'), v('차', 'cha', 'tea / car', '🍵'), v('하루', 'haru', 'one day', '📅'), v('호수', 'hosu', 'lake', '🏞️'), v('커피', 'keopi', 'coffee', '☕'), v('스키', 'seuki', 'ski', '⛷️')],
    grammar: [g('Plain vs aspirated', 'The puff-of-air test', 'Plain consonants (ㄱ ㄷ ㅂ ㅈ) have only a little air. Aspirated consonants (ㅋ ㅌ ㅍ ㅊ) push out a strong puff — the tissue moves!', [['가 ↔ 카', 'ga ↔ ka'], ['다 ↔ 타', 'da ↔ ta'], ['바 ↔ 파', 'ba ↔ pa'], ['자 ↔ 차', 'ja ↔ cha']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Say each pair. The second sound should move your tissue.',
      items: [p('가 카', 'ga ka', 'Relaxed → strong air.'), p('다 타', 'da ta'), p('바 파', 'ba pa'), p('자 차', 'ja cha'), p('하', 'ha'), p('카드', 'kadeu'), p('타조', 'tajo'), p('파도', 'pado'), p('치즈', 'chijeu'), p('커피', 'keopi')],
    },
    quiz: [
      listen('카', ['가', '카'], 1),
      listen('다', ['다', '타'], 0),
      listen('파', ['바', '파'], 1),
      listen('차', ['자', '차'], 1),
      listen('호수', ['오수', '호수'], 1),
      mc('Which consonant has a strong puff of air?', ['ㄱ', 'ㅋ', 'ㄴ', 'ㅁ'], 1),
      mc('☕ = ?', ['커피', '코피', '카드', '쿠키'], 0),
      mc('ㅊ + ㅣ = ?', ['지', '치', '시', '히'], 1),
    ],
    writing: { tip_en: 'ㅋ is ㄱ with a middle stroke; ㅌ is ㄷ with a middle stroke.', items: [w('ㅋ', 'k'), w('ㅌ', 't'), w('ㅍ', 'p'), w('ㅊ', 'ch'), w('ㅎ', 'h'), w('카', 'ka'), w('타', 'ta'), w('커피', 'keopi', 'coffee'), w('치즈', 'chijeu', 'cheese'), w('하루', 'haru', 'one day')] },
    culture: { title: 'Konglish', body_en: 'Many Korean words come from English: 카드 (card), 커피 (coffee), 치즈 (cheese). Because Korean syllables end in a vowel or a few consonants, English words gain an extra ㅡ: cheese → 치즈.' },
    chat: null,
  },

  // ───────────── 4과 경음 ─────────────
  {
    id: 'L04',
    unitId: 'U2',
    order: 21,
    kind: 'hangeul',
    title: { ko: '경음', en: 'Tense Consonants' },
    objectives: ['Hear and say ㄲ ㄸ ㅃ ㅆ ㅉ', 'Compare plain, aspirated and tense sounds', 'Read words with tense consonants'],
    warmup: { emoji: '💪', question_en: 'Say “sky”, “stop”, “spy”. The k, t, p after s have almost no air — that’s close to Korean tense sounds!' },
    letters: [
      L('ㄲ', 'kk', 'Tighten your throat, no air. Like “k” in “sky”.', '꼬마', 'kkoma', 'little kid', '쌍기역'),
      L('ㄸ', 'tt', 'Tight, no air. Like “t” in “stop”.', '따다', 'ttada', 'to pick', '쌍디귿'),
      L('ㅃ', 'pp', 'Tight, no air. Like “p” in “spy”.', '오빠', 'oppa', 'older brother (said by a girl)', '쌍비읍'),
      L('ㅆ', 'ss', 'A sharp, strong “s”.', '싸다', 'ssada', 'to be cheap', '쌍시옷'),
      L('ㅉ', 'jj', 'A tight “j”, no air.', '짜다', 'jjada', 'to be salty', '쌍지읒'),
    ],
    vocab: [v('꼬마', 'kkoma', 'little kid', '🧒'), v('까치', 'kkachi', 'magpie', '🐦'), v('따다', 'ttada', 'to pick', '🍒'), v('오빠', 'oppa', 'older brother (girl speaking)', '👦'), v('빠르다', 'ppareuda', 'to be fast', '⚡'), v('싸다', 'ssada', 'to be cheap', '🏷️'), v('아저씨', 'ajeossi', 'mister', '👨'), v('짜다', 'jjada', 'to be salty', '🧂'), v('가짜', 'gajja', 'fake', '🎭')],
    grammar: [g('Plain · aspirated · tense', 'Three families of sounds', 'Plain: relaxed, a little air. Aspirated: lots of air. Tense: no air, tight throat, a bit higher pitch.', [['가 · 카 · 까', 'ga · ka · kka'], ['다 · 타 · 따', 'da · ta · tta'], ['바 · 파 · 빠', 'ba · pa · ppa'], ['자 · 차 · 짜', 'ja · cha · jja'], ['사 · 싸', 'sa · ssa']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Say each set of three: relaxed → air → tight.',
      items: [p('가 카 까', 'ga ka kka'), p('다 타 따', 'da ta tta'), p('바 파 빠', 'ba pa ppa'), p('자 차 짜', 'ja cha jja'), p('사 싸', 'sa ssa'), p('꼬마', 'kkoma'), p('오빠', 'oppa'), p('아저씨', 'ajeossi'), p('짜다', 'jjada')],
    },
    quiz: [
      listen('까', ['가', '카', '까'], 2),
      listen('따', ['다', '타', '따'], 2),
      listen('파', ['바', '파', '빠'], 1),
      listen('싸', ['사', '싸'], 1),
      listen('자', ['자', '차', '짜'], 0),
      mc('Which sound has NO air and a tight throat?', ['ㅂ', 'ㅍ', 'ㅃ'], 2),
      mc('🧂 This soup is very… = ?', ['싸다', '짜다', '따다'], 1),
      listen('오빠', ['오바', '오파', '오빠'], 2),
    ],
    writing: { tip_en: 'Tense consonants are doubled: write the same letter twice, a little narrower.', items: [w('ㄲ', 'kk'), w('ㄸ', 'tt'), w('ㅃ', 'pp'), w('ㅆ', 'ss'), w('ㅉ', 'jj'), w('꼬마', 'kkoma', 'little kid'), w('오빠', 'oppa', 'older brother'), w('아저씨', 'ajeossi', 'mister')] },
    culture: { title: '빨리빨리!', body_en: 'Tense sounds feel fast and strong — like the famous expression 빨리빨리 (“quickly, quickly!”). Korea is known for very fast delivery and internet.' },
    chat: null,
  },

  // ───────────── 연습 활용 (2) ─────────────
  {
    id: 'R2',
    unitId: 'U2',
    order: 22,
    kind: 'hangeul',
    title: { ko: '연습 활용 (2)', en: 'Practice 2: Three Sound Families' },
    objectives: ['Review plain, aspirated and tense consonants', 'Hear the difference in real words'],
    warmup: { emoji: '🎧', question_en: 'Ready for a listening challenge? 불 (fire), 풀 (grass) and 뿔 (horn) differ only in the first sound!' },
    vocab: [v('불', 'bul', 'fire', '🔥'), v('풀', 'pul', 'grass / glue', '🌿'), v('뿔', 'ppul', 'horn', '🦏'), v('달', 'dal', 'moon', '🌙'), v('탈', 'tal', 'mask', '🎭'), v('딸', 'ttal', 'daughter', '👧'), v('자다', 'jada', 'to sleep', '😴'), v('차다', 'chada', 'to kick / to be cold', '🦶'), v('짜다', 'jjada', 'to be salty', '🧂')],
    grammar: [],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: { focus_en: 'Minimal pairs: only the first sound changes.', items: [p('불 풀 뿔', 'bul pul ppul'), p('달 탈 딸', 'dal tal ttal'), p('자다 차다 짜다', 'jada chada jjada'), p('고기 코끼리', 'gogi kokkiri', 'meat · elephant')] },
    quiz: [
      listen('풀', ['불', '풀', '뿔'], 1),
      listen('딸', ['달', '탈', '딸'], 2),
      listen('불', ['불', '풀', '뿔'], 0),
      listen('차다', ['자다', '차다', '짜다'], 1),
      listen('탈', ['달', '탈', '딸'], 1),
      mc('🌙 = ?', ['달', '탈', '딸'], 0),
      mc('Which word starts with a TENSE sound?', ['바다', '파도', '빠르다'], 2),
    ],
    writing: { tip_en: 'Write each set and say it aloud as you write.', items: [w('불', 'bul'), w('풀', 'pul'), w('뿔', 'ppul'), w('달', 'dal'), w('탈', 'tal'), w('딸', 'ttal')] },
    culture: null,
    chat: null,
  },

  // ───────────── 5과 이중 모음 1 ─────────────
  {
    id: 'L05',
    unitId: 'U3',
    order: 30,
    kind: 'hangeul',
    title: { ko: '이중 모음 1', en: 'Compound Vowels 1' },
    objectives: ['Learn ㅑ ㅕ, ㅛ ㅠ, ㅖ ㅒ', 'Understand “y + vowel” sounds', 'Read words with y-vowels'],
    warmup: { emoji: '➕', question_en: 'Add one more short stroke to ㅏ and you get ㅑ (ya). What do you think ㅛ sounds like?' },
    letters: [
      L('ㅑ', 'ya', 'ㅏ + one extra stroke = “y” + ㅏ.', '야구', 'yagu', 'baseball'),
      L('ㅕ', 'yeo', '“y” + ㅓ. Lips relaxed, not round.', '여우', 'yeou', 'fox'),
      L('ㅛ', 'yo', '“y” + ㅗ. Round lips.', '요리', 'yori', 'cooking'),
      L('ㅠ', 'yu', '“y” + ㅜ, like “you”.', '우유', 'uyu', 'milk'),
      L('ㅖ', 'ye', '“y” + ㅔ. After a consonant it is usually just [에]: 시계 [시게].', '시계', 'sigye', 'clock / watch'),
      L('ㅒ', 'yae', '“y” + ㅐ. Rare, but common in 얘기 (talk).', '얘기', 'yaegi', 'talk / story'),
    ],
    vocab: [v('야구', 'yagu', 'baseball', '⚾'), v('여우', 'yeou', 'fox', '🦊'), v('여자', 'yeoja', 'woman / girl', '👩'), v('요리', 'yori', 'cooking', '🍳'), v('우유', 'uyu', 'milk', '🥛'), v('휴지', 'hyuji', 'tissue', '🧻'), v('유리', 'yuri', 'glass', '🪟'), v('시계', 'sigye', 'clock / watch', '⌚', '[시게]'), v('예', 'ye', 'yes (polite)', '🙋'), v('얘기', 'yaegi', 'talk / story', '💬')],
    grammar: [g('y-vowels', 'One extra stroke = “y”', 'Double the short stroke and the vowel gains a “y” sound at the start.', [['ㅏ → ㅑ', 'a → ya'], ['ㅓ → ㅕ', 'eo → yeo'], ['ㅗ → ㅛ', 'o → yo'], ['ㅜ → ㅠ', 'u → yu'], ['ㅔ → ㅖ', 'e → ye'], ['ㅐ → ㅒ', 'ae → yae']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Start each sound with a quick “y” glide.',
      items: [p('야 여 요 유', 'ya yeo yo yu'), p('예 얘', 'ye yae'), p('아 야', 'a ya', 'Compare.'), p('오 요', 'o yo', 'Compare.'), p('야구', 'yagu'), p('여우', 'yeou'), p('우유', 'uyu'), p('시계', 'sigye', '[시게]')],
    },
    quiz: [
      listen('야', ['아', '야'], 1),
      listen('요', ['오', '요'], 1),
      listen('여', ['어', '여', '요'], 1),
      listen('유', ['우', '유', '요'], 1),
      mc('ㅇ + ㅛ = ?', ['오', '요', '유', '여'], 1),
      mc('🥛 = ?', ['우유', '유리', '요리', '야구'], 0),
      mc('How is 시계 pronounced?', ['[시계]', '[시게]', '[시개]'], 1),
      listen('여우', ['여우', '야우', '요우'], 0),
    ],
    writing: { tip_en: 'Write the long line first, then the two short strokes.', items: [w('ㅑ', 'ya'), w('ㅕ', 'yeo'), w('ㅛ', 'yo'), w('ㅠ', 'yu'), w('ㅖ', 'ye'), w('ㅒ', 'yae'), w('야구', 'yagu', 'baseball'), w('우유', 'uyu', 'milk'), w('시계', 'sigye', 'clock')] },
    culture: { title: 'Baseball fever', body_en: '야구 (baseball) is Korea’s most popular sport to watch. Fans sing team songs for every player and the games feel like big parties.' },
    chat: null,
  },

  // ───────────── 6과 이중 모음 2 ─────────────
  {
    id: 'L06',
    unitId: 'U3',
    order: 31,
    kind: 'hangeul',
    title: { ko: '이중 모음 2', en: 'Compound Vowels 2' },
    objectives: ['Learn ㅘ ㅝ ㅙ ㅞ and ㅚ ㅟ ㅢ', 'Understand “w + vowel” sounds', 'Know how ㅢ changes in different places'],
    warmup: { emoji: '🧩', question_en: 'ㅗ + ㅏ = ㅘ (wa). Vowels can be joined like puzzle pieces. What might ㅜ + ㅓ be?' },
    letters: [
      L('ㅘ', 'wa', 'ㅗ + ㅏ: start round, then open wide.', '사과', 'sagwa', 'apple'),
      L('ㅝ', 'wo', 'ㅜ + ㅓ: “wo” as in “won”.', '뭐', 'mwo', 'what'),
      L('ㅙ', 'wae', 'ㅗ + ㅐ: “we” as in “wet”.', '돼지', 'dwaeji', 'pig'),
      L('ㅞ', 'we', 'ㅜ + ㅔ: also “we”.', '웨이터', 'weiteo', 'waiter'),
      L('ㅚ', 'oe', 'Today usually said “we”, just like ㅙ and ㅞ.', '회사', 'hoesa', 'company'),
      L('ㅟ', 'wi', 'ㅜ + ㅣ: “wee”.', '귀', 'gwi', 'ear'),
      L('ㅢ', 'ui', 'ㅡ + ㅣ said quickly. At the start of a word: [의]. After a consonant: [이]. Meaning “of”: [에].', '의자', 'uija', 'chair'),
    ],
    vocab: [v('사과', 'sagwa', 'apple', '🍎'), v('과자', 'gwaja', 'snack', '🍘'), v('뭐', 'mwo', 'what', '❓'), v('돼지', 'dwaeji', 'pig', '🐷'), v('왜', 'wae', 'why', '🤔'), v('웨이터', 'weiteo', 'waiter', '🤵'), v('회사', 'hoesa', 'company', '🏢'), v('귀', 'gwi', 'ear', '👂'), v('가위', 'gawi', 'scissors', '✂️'), v('의자', 'uija', 'chair', '🪑'), v('의사', 'uisa', 'doctor', '🩺'), v('희다', 'huida', 'to be white', '⚪', '[히다]')],
    grammar: [
      g('w-vowels', 'ㅗ / ㅜ + another vowel', 'Start with rounded lips (ㅗ or ㅜ) and glide into the next vowel.', [['ㅗ + ㅏ = ㅘ', 'wa'], ['ㅜ + ㅓ = ㅝ', 'wo'], ['ㅗ + ㅐ = ㅙ', 'wae'], ['ㅜ + ㅔ = ㅞ', 'we'], ['ㅗ + ㅣ = ㅚ', 'oe'], ['ㅜ + ㅣ = ㅟ', 'wi']]),
      g('ㅢ', 'Three ways to say it', 'Word start: [의] 의사. After a consonant: [이] 희다 [히다]. As the particle “of”: usually [에].', [['의자 [의자]', 'chair'], ['희다 [히다]', 'to be white']]),
    ],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Glide smoothly from round lips to the second vowel. Watch Bori’s mouth change.',
      items: [p('와 워', 'wa wo'), p('왜 웨 외', 'wae we oe', 'All three sound almost the same today.'), p('위 의', 'wi ui'), p('사과', 'sagwa'), p('돼지', 'dwaeji'), p('회사', 'hoesa'), p('귀', 'gwi'), p('의자', 'uija')],
    },
    quiz: [
      listen('와', ['와', '워'], 0),
      listen('위', ['위', '의'], 0),
      listen('사과', ['사가', '사과', '사고'], 1),
      listen('의사', ['의사', '위사', '이사'], 0),
      mc('ㅜ + ㅓ = ?', ['ㅘ', 'ㅝ', 'ㅟ', 'ㅢ'], 1),
      mc('👂 = ?', ['귀', '게', '가위', '개'], 0),
      mc('🐷 = ?', ['돼지', '뒤지', '되지'], 0),
      mc('How is 희다 pronounced?', ['[희다]', '[히다]', '[흐다]'], 1),
    ],
    writing: { tip_en: 'Write the first vowel, then the second one next to it.', items: [w('ㅘ', 'wa'), w('ㅝ', 'wo'), w('ㅙ', 'wae'), w('ㅞ', 'we'), w('ㅚ', 'oe'), w('ㅟ', 'wi'), w('ㅢ', 'ui'), w('사과', 'sagwa', 'apple'), w('돼지', 'dwaeji', 'pig'), w('의자', 'uija', 'chair')] },
    culture: { title: '“뭐?” and “왜?” in K-dramas', body_en: 'You will hear 뭐? (What?) and 왜? (Why?) in almost every K-drama, often with a lot of surprise. Listen for them in the Drama Studio!' },
    chat: null,
  },

  // ───────────── 연습 활용 (3) ─────────────
  {
    id: 'R3',
    unitId: 'U3',
    order: 32,
    kind: 'hangeul',
    title: { ko: '연습 활용 (3)', en: 'Practice 3: All the Vowels' },
    objectives: ['Review all 21 vowels', 'Read words with compound vowels'],
    warmup: { emoji: '🏁', question_en: 'You have now met every Korean vowel — 21 of them! Can you say them all with Bori?' },
    vocab: [v('교사', 'gyosa', 'teacher', '🧑‍🏫'), v('여유', 'yeoyu', 'free time / room', '🛋️'), v('과제', 'gwaje', 'assignment', '📝'), v('위기', 'wigi', 'crisis', '⚠️'), v('예의', 'yeui', 'manners', '🙇', '[예이]'), v('바위', 'bawi', 'rock', '🪨'), v('샤워', 'syawo', 'shower', '🚿'), v('뭐예요', 'mwoyeyo', 'what is it?', '❓')],
    grammar: [],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: { focus_en: 'Mix of simple and compound vowels.', items: [p('교사', 'gyosa'), p('과제', 'gwaje'), p('바위', 'bawi'), p('샤워', 'syawo'), p('예의', 'yeui', '[예이]'), p('뭐예요?', 'mwoyeyo?')] },
    quiz: [
      listen('과제', ['고제', '과제', '구제'], 1),
      listen('바위', ['바이', '바위', '바우'], 1),
      listen('샤워', ['사워', '샤워', '샤오'], 1),
      mc('Which vowel is NOT a compound vowel?', ['ㅘ', 'ㅕ', 'ㅓ', 'ㅢ'], 2),
      mc('🚿 = ?', ['샤워', '사과', '시계'], 0),
      mc('ㄱ + ㅛ = ?', ['교', '규', '갸', '겨'], 0),
    ],
    writing: { tip_en: 'Say each word out loud while you write it.', items: [w('교사', 'gyosa', 'teacher'), w('과제', 'gwaje', 'assignment'), w('바위', 'bawi', 'rock'), w('샤워', 'syawo', 'shower')] },
    culture: null,
    chat: null,
  },

  // ───────────── 7과 받침 1 ─────────────
  {
    id: 'L07',
    unitId: 'U4',
    order: 40,
    kind: 'hangeul',
    title: { ko: '받침 1', en: 'Final Consonants 1' },
    objectives: ['Learn the final consonants ㅁ, ㅇ, ㄴ, ㄹ', 'Write syllables with a final consonant (받침)', 'Read words with ㅁ ㅇ ㄴ ㄹ finals'],
    warmup: { emoji: '🧱', question_en: 'In 밤 (night), the second ㅁ sits at the bottom of the block. That bottom consonant is called 받침, “the support”.' },
    letters: [
      L('ㅁ', 'm', 'Close the lips and hum: [m].', '밤', 'bam', 'night'),
      L('ㅇ', 'ng', 'At the bottom ㅇ is NOT silent: [ng] as in “song”.', '공', 'gong', 'ball'),
      L('ㄴ', 'n', 'Tongue tip touches the gum ridge: [n].', '산', 'san', 'mountain'),
      L('ㄹ', 'l', 'Tongue tip stays up on the roof of the mouth: [l].', '물', 'mul', 'water'),
    ],
    vocab: [v('밤', 'bam', 'night', '🌃'), v('감', 'gam', 'persimmon', '🟠'), v('김치', 'gimchi', 'kimchi', '🥬'), v('공', 'gong', 'ball', '⚽'), v('방', 'bang', 'room', '🚪'), v('가방', 'gabang', 'bag', '🎒'), v('산', 'san', 'mountain', '⛰️'), v('눈', 'nun', 'eye / snow', '👁️'), v('라면', 'ramyeon', 'ramen', '🍜'), v('물', 'mul', 'water', '💧'), v('달', 'dal', 'moon', '🌕'), v('일', 'il', 'one / work', '1️⃣')],
    grammar: [g('Syllable + 받침', 'The final consonant goes at the bottom', 'A syllable can have a third part. The final consonant always sits at the bottom of the block.', [['ㅂ + ㅏ + ㅁ = 밤', 'night'], ['ㄱ + ㅗ + ㅇ = 공', 'ball'], ['ㅅ + ㅏ + ㄴ = 산', 'mountain'], ['ㅁ + ㅜ + ㄹ = 물', 'water']]), g('Humming finals', 'ㅁ ㅇ ㄴ ㄹ keep sounding', 'These four finals can be held long: mmm, nnn, ngng, lll. Don’t add a vowel after them: 물 is [mul], not “mu-ru”.', [['밤 [bam]', 'not “ba-mu”'], ['물 [mul]', 'not “mu-ru”']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Hold the final sound — don’t add an extra vowel.',
      items: [p('밤', 'bam'), p('공', 'gong'), p('산', 'san'), p('물', 'mul'), p('감 강 간 갈', 'gam gang gan gal', 'Only the final changes.'), p('가방', 'gabang'), p('라면', 'ramyeon'), p('김치', 'gimchi')],
    },
    quiz: [
      listen('밤', ['밤', '방', '반'], 0),
      listen('공', ['곰', '공', '곤'], 1),
      listen('산', ['삼', '상', '산'], 2),
      listen('물', ['문', '물', '뭄'], 1),
      listen('강', ['감', '강', '간', '갈'], 1),
      mc('ㅂ + ㅏ + ㅇ = ?', ['방', '밤', '반', '발'], 0),
      mc('🍜 = ?', ['라면', '김치', '가방'], 0),
      mc('In 공, the final ㅇ sounds like…', ['nothing (silent)', '[ng]', '[n]'], 1),
    ],
    writing: { tip_en: 'Write the first consonant and vowel a little smaller, then put the 받침 underneath.', items: [w('밤', 'bam', 'night'), w('공', 'gong', 'ball'), w('산', 'san', 'mountain'), w('물', 'mul', 'water'), w('가방', 'gabang', 'bag'), w('라면', 'ramyeon', 'ramen')] },
    culture: { title: '김치', body_en: 'Kimchi is served with almost every Korean meal. In late autumn, families gather to make a whole winter’s supply together — this tradition is called 김장.' },
    chat: null,
  },

  // ───────────── 8과 받침 2 ─────────────
  {
    id: 'L08',
    unitId: 'U4',
    order: 41,
    kind: 'hangeul',
    title: { ko: '받침 2', en: 'Final Consonants 2' },
    objectives: ['Learn the final sounds [ㄱ], [ㅂ], [ㄷ]', 'Know which letters share the same final sound', 'Read words with stopped finals'],
    warmup: { emoji: '✋', question_en: 'Say “book” but stop before the k fully comes out. That stopped sound is how Korean final ㄱ works.' },
    letters: [
      L('ㄱ', 'k', 'ㄱ ㅋ ㄲ at the bottom all sound [ㄱ]: stop the air at the back of the throat, no release.', '책', 'chaek', 'book', '받침 [ㄱ]'),
      L('ㅂ', 'p', 'ㅂ ㅍ at the bottom sound [ㅂ]: close the lips and stop.', '밥', 'bap', 'rice / meal', '받침 [ㅂ]'),
      L('ㄷ', 't', 'ㄷ ㅌ ㅅ ㅆ ㅈ ㅊ ㅎ at the bottom all sound [ㄷ]: tongue tip stops behind the teeth.', '옷', 'ot', 'clothes', '받침 [ㄷ]'),
    ],
    vocab: [v('책', 'chaek', 'book', '📕'), v('국', 'guk', 'soup', '🍲'), v('부엌', 'bueok', 'kitchen', '🍳', '[부억]'), v('밖', 'bak', 'outside', '🌳', '[박]'), v('밥', 'bap', 'rice / meal', '🍚'), v('입', 'ip', 'mouth', '👄'), v('앞', 'ap', 'front', '⬆️', '[압]'), v('옷', 'ot', 'clothes', '👕', '[옫]'), v('낮', 'nat', 'daytime', '☀️', '[낟]'), v('꽃', 'kkot', 'flower', '🌸', '[꼳]'), v('밭', 'bat', 'field', '🌾', '[받]'), v('맛', 'mat', 'taste', '😋', '[맏]')],
    grammar: [g('Seven final sounds', 'Many letters, few sounds', 'Any consonant can be written as 받침, but only 7 sounds are pronounced at the end of a syllable: [ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅇ].', [['ㄱ ㅋ ㄲ → [ㄱ]', '책, 부엌 [부억], 밖 [박]'], ['ㅂ ㅍ → [ㅂ]', '밥, 앞 [압]'], ['ㄷ ㅌ ㅅ ㅆ ㅈ ㅊ ㅎ → [ㄷ]', '옷 [옫], 낮 [낟], 꽃 [꼳]']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Final [ㄱ], [ㅂ], [ㄷ] are not released — stop the sound without a puff of air.',
      items: [p('책', 'chaek', 'Stop at the back of the throat.'), p('밥', 'bap', 'Lips stay closed at the end.'), p('옷', 'ot', 'Sounds [옫].'), p('꽃', 'kkot', '[꼳]'), p('앞', 'ap', '[압]'), p('부엌', 'bueok', '[부억]'), p('낮', 'nat', '[낟]'), p('국 굽 굳', 'guk gup gut', 'Compare the three stops.')],
    },
    quiz: [
      listen('책', ['책', '챕', '챋'], 0),
      listen('밥', ['박', '밥', '받'], 1),
      listen('입', ['익', '입', '인'], 1),
      mc('How is 옷 pronounced?', ['[옷]', '[옫]', '[오]', '[오시]'], 1),
      mc('How is 앞 pronounced?', ['[압]', '[악]', '[앗]'], 0),
      mc('Which final sounds like [ㄷ]?', ['ㅂ', 'ㅈ', 'ㄱ', 'ㅁ'], 1),
      mc('🌸 = ?', ['꽃', '꼭', '꼽'], 0),
      listen('국', ['국', '굽', '굳'], 0),
    ],
    writing: { tip_en: 'Write the 받침 you SEE, even though it sounds like another letter: 옷, not 옫.', items: [w('책', 'chaek', 'book'), w('밥', 'bap', 'rice'), w('옷', 'ot', 'clothes'), w('꽃', 'kkot', 'flower'), w('부엌', 'bueok', 'kitchen'), w('앞', 'ap', 'front')] },
    culture: { title: '밥 means more than rice', body_en: '밥 is cooked rice, but also “a meal”. Koreans often ask 밥 먹었어요? (Did you eat?) as a friendly way to say “How are you?”.' },
    chat: null,
  },

  // ───────────── 연습 활용 (4) ─────────────
  {
    id: 'R4',
    unitId: 'U4',
    order: 42,
    kind: 'hangeul',
    title: { ko: '연습 활용 (4)', en: 'Practice 4: Final Consonants' },
    objectives: ['Review all seven final sounds', 'Hear which final a word ends with'],
    warmup: { emoji: '🧩', question_en: 'Same start, different ending: 감, 강, 간, 갈, 각, 갑, 갇. Can you hear all seven?' },
    vocab: [v('곰', 'gom', 'bear', '🐻'), v('빵', 'ppang', 'bread', '🍞'), v('문', 'mun', 'door', '🚪'), v('발', 'bal', 'foot', '🦶'), v('약', 'yak', 'medicine', '💊'), v('집', 'jip', 'house', '🏠'), v('듣다', 'deutda', 'to listen', '🎧', '[듣따]'), v('수업', 'sueop', 'class', '🏫')],
    grammar: [],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: { focus_en: 'Seven finals: [ㄱ ㄴ ㄷ ㄹ ㅁ ㅂ ㅇ].', items: [p('감 강 간 갈', 'gam gang gan gal'), p('각 갑 갇', 'gak gap gat'), p('곰', 'gom'), p('빵', 'ppang'), p('집', 'jip'), p('수업', 'sueop')] },
    quiz: [
      listen('곰', ['곰', '공', '곤'], 0),
      listen('문', ['문', '물', '뭉'], 0),
      listen('집', ['직', '집', '짓'], 1),
      listen('약', ['약', '얍', '얀'], 0),
      mc('Which word ends with the sound [ㅇ]?', ['곰', '빵', '문', '발'], 1),
      mc('🏠 = ?', ['집', '짐', '진'], 0),
    ],
    writing: { tip_en: 'One syllable per box.', items: [w('곰', 'gom', 'bear'), w('빵', 'ppang', 'bread'), w('문', 'mun', 'door'), w('집', 'jip', 'house'), w('수업', 'sueop', 'class')] },
    culture: null,
    chat: null,
  },

  // ───────────── 9과 겹받침 ─────────────
  {
    id: 'L09',
    unitId: 'U5',
    order: 50,
    kind: 'hangeul',
    title: { ko: '겹받침', en: 'Double Final Consonants' },
    objectives: ['Learn ㄺ, ㄼ ㅀ, ㅄ ㄵ ㄶ', 'Know which of the two letters is pronounced', 'Read common words with double finals'],
    warmup: { emoji: '✌️', question_en: 'Some syllables carry TWO consonants at the bottom, like 닭 (chicken). But you only pronounce one of them — which one?' },
    letters: [
      L('ㄺ', 'k', 'Usually pronounced [ㄱ]: 닭 [닥], 맑다 [막따].', '닭', 'dak', 'chicken', '[ㄱ]'),
      L('ㄼ', 'l', 'Usually pronounced [ㄹ]: 여덟 [여덜], 넓다 [널따].', '여덟', 'yeodeol', 'eight', '[ㄹ]'),
      L('ㅀ', 'l', 'Pronounced [ㄹ]; the ㅎ makes the next sound strong: 싫다 [실타].', '싫다', 'silta', 'to dislike', '[ㄹ]'),
      L('ㅄ', 'p', 'Pronounced [ㅂ]: 값 [갑], 없다 [업따].', '값', 'gap', 'price', '[ㅂ]'),
      L('ㄵ', 'n', 'Pronounced [ㄴ]: 앉다 [안따].', '앉다', 'anda', 'to sit', '[ㄴ]'),
      L('ㄶ', 'n', 'Pronounced [ㄴ]; the ㅎ makes the next sound strong: 많다 [만타].', '많다', 'manta', 'to be many', '[ㄴ]'),
    ],
    vocab: [v('닭', 'dak', 'chicken', '🐔', '[닥]'), v('맑다', 'makda', 'to be clear (sky)', '☀️', '[막따]'), v('여덟', 'yeodeol', 'eight', '8️⃣', '[여덜]'), v('넓다', 'neolda', 'to be wide', '↔️', '[널따]'), v('짧다', 'jjalda', 'to be short', '📏', '[짤따]'), v('싫다', 'silta', 'to dislike', '🙅', '[실타]'), v('값', 'gap', 'price', '🏷️', '[갑]'), v('없다', 'eopda', 'to not have', '🚫', '[업따]'), v('앉다', 'anda', 'to sit', '🪑', '[안따]'), v('많다', 'manta', 'to be many', '📚', '[만타]'), v('괜찮다', 'gwaenchanta', 'to be okay', '👌', '[괜찬타]')],
    grammar: [g('Which letter do you say?', 'Only one of the two finals is pronounced', 'Before a consonant or at the end of a word, only one consonant of the pair is pronounced.', [['ㄺ → [ㄱ]', '닭 [닥]'], ['ㄼ, ㅀ → [ㄹ]', '여덟 [여덜], 싫다 [실타]'], ['ㅄ → [ㅂ]', '값 [갑]'], ['ㄵ, ㄶ → [ㄴ]', '앉다 [안따], 많다 [만타]']]), g('ㅎ makes the next sound strong', 'ㄶ ㅀ + ㄱ/ㄷ/ㅈ', 'When the hidden ㅎ meets ㄱ, ㄷ or ㅈ, they become ㅋ, ㅌ, ㅊ.', [['많다 → [만타]', 'ㅎ + ㄷ = ㅌ'], ['싫다 → [실타]', 'ㅎ + ㄷ = ㅌ']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Say only one of the two final letters.',
      items: [p('닭', 'dak', '[닥]'), p('여덟', 'yeodeol', '[여덜]'), p('값', 'gap', '[갑]'), p('없다', 'eopda', '[업따]'), p('앉다', 'anda', '[안따]'), p('많다', 'manta', '[만타]'), p('싫다', 'silta', '[실타]'), p('괜찮다', 'gwaenchanta', '[괜찬타]')],
    },
    quiz: [
      mc('How is 닭 pronounced?', ['[달]', '[닥]', '[닭]'], 1),
      mc('How is 값 pronounced?', ['[갑]', '[갓]', '[감]'], 0),
      mc('How is 많다 pronounced?', ['[만다]', '[만타]', '[마나]'], 1),
      mc('How is 여덟 pronounced?', ['[여덥]', '[여덜]', '[여더]'], 1),
      listen('없다', ['업다', '없다', '엇다'], 1, 'Listen. Which word is it (spelling)?'),
      listen('앉다', ['앉다', '안다', '않다'], 0, 'Listen. Which word is it (spelling)? Hint: “to sit”.'),
      mc('🐔 = ?', ['닭', '달', '닥'], 0),
    ],
    writing: { tip_en: 'Write both final letters side by side under the vowel.', items: [w('닭', 'dak', 'chicken'), w('값', 'gap', 'price'), w('여덟', 'yeodeol', 'eight'), w('앉다', 'anda', 'to sit'), w('많다', 'manta', 'to be many')] },
    culture: { title: '치킨 culture', body_en: 'Korean fried chicken (치킨) — often with beer for adults or cola for students — is a national favorite. 닭 is the animal; 치킨 is the delicious fried dish!' },
    chat: null,
  },

  // ───────────── 10과 연음 ─────────────
  {
    id: 'L10',
    unitId: 'U5',
    order: 51,
    kind: 'hangeul',
    title: { ko: '연음', en: 'Linking Sounds' },
    objectives: ['Understand basic linking (연음)', 'Link double finals into the next syllable', 'Know that final ㅎ goes silent before a vowel'],
    warmup: { emoji: '🔗', question_en: 'Write 한국어, but say [한구거]. When a final consonant meets the silent ㅇ, it slides over. That is 연음.' },
    vocab: [v('한국어', 'hangugeo', 'Korean language', '🗣️', '[한구거]'), v('음악', 'eumak', 'music', '🎵', '[으막]'), v('발음', 'bareum', 'pronunciation', '👄', '[바름]'), v('직업', 'jigeop', 'job', '💼', '[지겁]'), v('먹어요', 'meogeoyo', '(I) eat', '🍚', '[머거요]'), v('읽어요', 'ilgeoyo', '(I) read', '📖', '[일거요]'), v('없어요', 'eopseoyo', 'there isn’t', '🚫', '[업써요]'), v('앉아요', 'anjayo', '(I) sit', '🪑', '[안자요]'), v('좋아요', 'joayo', 'good / I like it', '👍', '[조아요]'), v('많아요', 'manayo', 'there are many', '📚', '[마나요]'), v('괜찮아요', 'gwaenchanayo', 'it’s okay', '👌', '[괜차나요]')],
    grammar: [g('Basic linking', 'Final consonant + ㅇ → slides over', 'When the next syllable starts with the silent ㅇ, the final consonant moves into that empty spot.', [['음악 → [으막]', 'music'], ['한국어 → [한구거]', 'Korean'], ['먹어요 → [머거요]', 'eat']]), g('Double finals', 'The second letter slides over', 'With a double final, the first letter stays and the second one moves.', [['읽어요 → [일거요]', 'ㄺ: ㄹ stays, ㄱ moves'], ['없어요 → [업써요]', 'ㅄ: ㅂ stays, ㅅ moves (and becomes ㅆ)'], ['앉아요 → [안자요]', 'ㄵ: ㄴ stays, ㅈ moves']]), g('Final ㅎ + vowel', 'ㅎ disappears', 'Final ㅎ (alone or in ㄶ/ㅀ) is silent before a vowel.', [['좋아요 → [조아요]', 'good'], ['많아요 → [마나요]', 'many'], ['싫어요 → [시러요]', 'I don’t like it']])],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: {
      focus_en: 'Read the spelling, say the [pronunciation].',
      items: [p('한국어', 'hangugeo', '[한구거]'), p('음악', 'eumak', '[으막]'), p('발음', 'bareum', '[바름]'), p('읽어요', 'ilgeoyo', '[일거요]'), p('없어요', 'eopseoyo', '[업써요]'), p('앉아요', 'anjayo', '[안자요]'), p('좋아요', 'joayo', '[조아요]'), p('괜찮아요', 'gwaenchanayo', '[괜차나요]')],
    },
    quiz: [
      mc('How is 음악 pronounced?', ['[음악]', '[으막]', '[음막]'], 1),
      mc('How is 읽어요 pronounced?', ['[이거요]', '[일거요]', '[읽어요]'], 1),
      mc('How is 좋아요 pronounced?', ['[조하요]', '[조아요]', '[좋아요]'], 1),
      mc('How is 없어요 pronounced?', ['[어버요]', '[업써요]', '[업어요]'], 1),
      listen('직업', ['직업', '지겁', '직어'], 0, 'Listen. Which SPELLING matches?'),
      mc('👍 = ?', ['좋아요', '많아요', '없어요'], 0),
    ],
    writing: { tip_en: 'Write the spelling — not the pronunciation!', items: [w('한국어', 'hangugeo', 'Korean'), w('음악', 'eumak', 'music'), w('읽어요', 'ilgeoyo', 'I read'), w('좋아요', 'joayo', 'good'), w('괜찮아요', 'gwaenchanayo', 'it’s okay')] },
    culture: { title: 'Why spelling ≠ sound', body_en: 'Korean spelling keeps the original form of each word part so meaning stays clear: 읽- (read) + -어요. Then sound rules like 연음 make speech smooth. Learn both: write the spelling, say the sound.' },
    chat: null,
  },

  // ───────────── 연습 활용 (5) ─────────────
  {
    id: 'R5',
    unitId: 'U5',
    order: 52,
    kind: 'hangeul',
    title: { ko: '연습 활용 (5)', en: 'Practice 5: Double Finals & Linking' },
    objectives: ['Review double finals and linking', 'Read whole words smoothly'],
    warmup: { emoji: '🏆', question_en: 'Last review before real expressions! Can you read 읽어요, 앉아요 and 많아요 smoothly?' },
    vocab: [v('밝아요', 'balgayo', 'it’s bright', '💡', '[발가요]'), v('넓어요', 'neolbeoyo', 'it’s wide', '↔️', '[널버요]'), v('짧아요', 'jjalbayo', 'it’s short', '📏', '[짤바요]'), v('싫어요', 'sireoyo', 'I don’t like it', '🙅', '[시러요]'), v('일요일', 'iryoil', 'Sunday', '📅', '[이료일]'), v('졸업', 'joreop', 'graduation', '🎓', '[조럽]')],
    grammar: [],
    dialogue: { setting_en: '', lines: [] },
    pronunciation: { focus_en: 'Link each final consonant into the next syllable.', items: [p('밝아요', 'balgayo', '[발가요]'), p('넓어요', 'neolbeoyo', '[널버요]'), p('짧아요', 'jjalbayo', '[짤바요]'), p('싫어요', 'sireoyo', '[시러요]'), p('일요일', 'iryoil', '[이료일]'), p('졸업', 'joreop', '[조럽]')] },
    quiz: [
      mc('How is 일요일 pronounced?', ['[일요일]', '[이료일]', '[이요일]'], 1),
      mc('How is 싫어요 pronounced?', ['[실허요]', '[시러요]', '[실어요]'], 1),
      mc('How is 넓어요 pronounced?', ['[널버요]', '[너버요]', '[넙어요]'], 0),
      listen('졸업', ['졸업', '조럽', '졸어'], 0, 'Listen. Which SPELLING matches?'),
      mc('🎓 = ?', ['졸업', '직업', '수업'], 0),
    ],
    writing: { tip_en: 'Write the spelling, then say it with linking.', items: [w('밝아요', 'balgayo', 'bright'), w('짧아요', 'jjalbayo', 'short'), w('일요일', 'iryoil', 'Sunday'), w('졸업', 'joreop', 'graduation')] },
    culture: null,
    chat: null,
  },

  // ───────────── 11과 표현 1 (교실 표현) ─────────────
  {
    id: 'L11',
    unitId: 'U6',
    order: 60,
    kind: 'standard',
    title: { ko: '표현 1', en: 'Classroom Expressions' },
    objectives: ['Understand what the teacher asks you to do', 'Answer with 네 / 아니요, 알겠어요 / 모르겠어요', 'Ask “Do you have a question?”'],
    warmup: { emoji: '🏫', question_en: 'In class, what does your teacher say most often? “Look”, “Listen”, “Repeat after me”…? Let’s learn them in Korean.' },
    vocab: [
      v('보세요', 'boseyo', 'please look', '👀'),
      v('들으세요', 'deureuseyo', 'please listen', '👂', '[드르세요]'),
      v('읽으세요', 'ilgeuseyo', 'please read', '📖', '[일그세요]'),
      v('쓰세요', 'sseuseyo', 'please write', '✍️'),
      v('말하세요', 'malhaseyo', 'please speak', '🗣️'),
      v('이야기하세요', 'iyagihaseyo', 'please talk (with a partner)', '💬'),
      v('따라 하세요', 'ttara haseyo', 'please repeat after me', '🔁'),
      v('쉬세요', 'swiseyo', 'take a break', '☕'),
      v('좋아요', 'joayo', 'good', '👍', '[조아요]'),
      v('잘했어요', 'jalhaesseoyo', 'well done', '🌟', '[잘해써요]'),
      v('질문 있어요?', 'jilmun isseoyo?', 'any questions?', '🙋', '[질문 이써요]'),
      v('알겠어요', 'algesseoyo', 'I understand / got it', '✅', '[알게써요]'),
      v('모르겠어요', 'moreugesseoyo', 'I don’t know / understand', '🤷', '[모르게써요]'),
    ],
    grammar: [
      g('-(으)세요', 'Polite request: “please do…”', 'Teachers use -(으)세요 to ask students to do something. After a consonant add -으세요; after a vowel add -세요.', [['보다 → 보세요', 'look'], ['읽다 → 읽으세요', 'read'], ['쓰다 → 쓰세요', 'write']]),
      g('있어요? / 없어요', 'Do you have…? / I don’t have…', 'Answer a question with 네 (yes) or 아니요 (no).', [['질문 있어요? — 네, 있어요.', 'Any questions? — Yes.'], ['질문 있어요? — 아니요, 없어요.', 'Any questions? — No.']]),
    ],
    dialogue: {
      setting_en: 'A Korean class at a weekend Korean school. The teacher is starting a reading activity.',
      lines: [
        line('선생님', '여러분, 칠판을 보세요.', 'Yeoreobun, chilpaneul boseyo.', 'Everyone, look at the board.'),
        line('선생님', '잘 들으세요. 그리고 따라 하세요. “안녕하세요.”', 'Jal deureuseyo. Geurigo ttara haseyo. “Annyeonghaseyo.”', 'Listen carefully. Then repeat after me. “Hello.”'),
        line('학생들', '안녕하세요.', 'Annyeonghaseyo.', 'Hello.'),
        line('선생님', '잘했어요! 이제 책을 읽으세요.', 'Jalhaesseoyo! Ije chaegeul ilgeuseyo.', 'Well done! Now read the book.'),
        line('에마', '선생님, 모르겠어요.', 'Seonsaengnim, moreugesseoyo.', 'Teacher, I don’t understand.'),
        line('선생님', '괜찮아요. 다시 들으세요.', 'Gwaenchanayo. Dasi deureuseyo.', 'That’s okay. Listen again.'),
        line('에마', '아, 알겠어요!', 'A, algesseoyo!', 'Oh, I get it!'),
        line('선생님', '좋아요. 질문 있어요?', 'Joayo. Jilmun isseoyo?', 'Good. Any questions?'),
        line('민준', '아니요, 없어요.', 'Aniyo, eopseoyo.', 'No, none.'),
      ],
    },
    pronunciation: {
      focus_en: 'Linking appears everywhere: 들으세요 [드르세요], 읽으세요 [일그세요], 있어요 [이써요].',
      items: [p('보세요', 'boseyo'), p('들으세요', 'deureuseyo', '[드르세요]'), p('읽으세요', 'ilgeuseyo', '[일그세요]'), p('쓰세요', 'sseuseyo'), p('따라 하세요', 'ttara haseyo'), p('잘했어요', 'jalhaesseoyo', '[잘해써요]'), p('질문 있어요?', 'jilmun isseoyo?', '[질문 이써요]'), p('알겠어요', 'algesseoyo', '[알게써요]'), p('모르겠어요', 'moreugesseoyo', '[모르게써요]')],
    },
    quiz: [
      mc('Your teacher points at their ear. What do they say?', ['보세요', '들으세요', '쓰세요', '쉬세요'], 1),
      mc('Your teacher hands you a pencil and paper. What do they say?', ['쓰세요', '읽으세요', '말하세요'], 0),
      listen('따라 하세요', ['따라 하세요', '말하세요', '쉬세요'], 0),
      mc('You understand the explanation. What do you say?', ['모르겠어요', '알겠어요', '없어요'], 1),
      mc('질문 있어요? — You have no question. Answer:', ['네, 있어요.', '아니요, 없어요.', '잘했어요.'], 1),
      mc('How is 읽으세요 pronounced?', ['[이그세요]', '[일그세요]', '[읽으세요]'], 1),
      order('Everyone, look at the board.', ['여러분,', '칠판을', '보세요.']),
    ],
    writing: { tip_en: 'Write each expression with the right spacing.', items: [w('보세요', 'boseyo', 'look'), w('들으세요', 'deureuseyo', 'listen'), w('읽으세요', 'ilgeuseyo', 'read'), w('쓰세요', 'sseuseyo', 'write'), w('알겠어요', 'algesseoyo', 'I understand'), w('모르겠어요', 'moreugesseoyo', 'I don’t understand')] },
    culture: { title: 'Teacher = 선생님', body_en: 'Students in Korea call their teacher 선생님 (teacher + respectful 님), never by first name. When you don’t understand, saying 모르겠어요 is polite and normal — teachers love questions!' },
    chat: {
      scenario: 'Bori is a friendly Korean teacher giving simple classroom instructions (보세요, 들으세요, 읽으세요, 쓰세요, 따라 하세요). The student answers with 네, 알겠어요, 모르겠어요, 질문 있어요 and repeats short phrases. Keep every sentence very short — the student has just learned Hangeul.',
      goal_en: 'Respond to classroom instructions with 네, 알겠어요 or 모르겠어요.',
      starter_ko: '안녕하세요! 수업 시작해요. 칠판을 보세요.',
      vocab: ['보세요', '들으세요', '읽으세요', '쓰세요', '따라 하세요', '알겠어요', '모르겠어요', '질문 있어요'],
    },
  },

  // ───────────── 12과 표현 2 (인사 표현) ─────────────
  {
    id: 'L12',
    unitId: 'U6',
    order: 61,
    kind: 'standard',
    title: { ko: '표현 2', en: 'Greetings & Courtesy' },
    objectives: ['Greet people when you meet for the first time', 'Say thank you, sorry and reply', 'Use mealtime and goodbye expressions'],
    warmup: { emoji: '🙇', question_en: 'In Korea people bow a little when they greet. How many ways do you know to say “hello” in your language?' },
    vocab: [
      v('안녕하세요?', 'annyeonghaseyo?', 'Hello', '👋'),
      v('안녕하십니까?', 'annyeonghasimnikka?', 'Hello (very formal)', '🎩', '[안녕하심니까]'),
      v('처음 뵙겠습니다', 'cheoeum boepgetseumnida', 'Nice to meet you (first meeting, formal)', '🤝', '[처음 뵙껟씀니다]'),
      v('만나서 반가워요', 'mannaseo bangawoyo', 'Nice to meet you', '😊'),
      v('감사합니다', 'gamsahamnida', 'Thank you', '🙏', '[감사함니다]'),
      v('고마워요', 'gomawoyo', 'Thanks', '💛'),
      v('아니에요', 'anieyo', 'Not at all / You’re welcome', '🙂'),
      v('죄송합니다', 'joesonghamnida', 'I’m sorry (formal)', '🙇', '[죄송함니다]'),
      v('미안해요', 'mianhaeyo', 'Sorry', '😅'),
      v('괜찮아요', 'gwaenchanayo', 'It’s okay', '👌', '[괜차나요]'),
      v('잘 먹겠습니다', 'jal meokgetseumnida', 'Thank you for the food (before eating)', '🍚', '[잘 먹껟씀니다]'),
      v('잘 먹었습니다', 'jal meogeotseumnida', 'I enjoyed the meal (after eating)', '😋', '[잘 머걷씀니다]'),
      v('생일 축하해요', 'saengil chukahaeyo', 'Happy birthday', '🎂', '[생일 추카해요]'),
      v('안녕히 가세요', 'annyeonghi gaseyo', 'Goodbye (to someone leaving)', '🚶'),
      v('안녕히 계세요', 'annyeonghi gyeseyo', 'Goodbye (to someone staying)', '🏠', '[안녕히 게세요]'),
      v('또 봐요', 'tto bwayo', 'See you again', '👀'),
    ],
    grammar: [
      g('Formal vs polite', '-습니다 vs -아요/어요', 'Endings in -ㅂ니다/습니다 sound formal (speeches, first meetings with adults). -아요/어요 is polite and friendly. 안녕 / 잘 가 are casual — only with close friends.', [['감사합니다 / 고마워요', 'formal / polite thanks'], ['죄송합니다 / 미안해요', 'formal / polite sorry'], ['안녕하세요 / 안녕', 'polite / casual hello']]),
      g('가세요 vs 계세요', 'Two different goodbyes', '안녕히 가세요 = “go well” to the person LEAVING. 안녕히 계세요 = “stay well” to the person STAYING when you leave.', [['(Your friend leaves) 안녕히 가세요!', 'they leave'], ['(You leave the classroom) 안녕히 계세요!', 'you leave']]),
    ],
    dialogue: {
      setting_en: 'Haneul, a new exchange student, meets Minjun and his mother at their home for dinner.',
      lines: [
        line('하늘', '안녕하세요? 처음 뵙겠습니다. 저는 하늘이에요.', 'Annyeonghaseyo? Cheoeum boepgetseumnida. Jeoneun Haneurieyo.', 'Hello. Nice to meet you. I’m Haneul.'),
        line('어머니', '반가워요, 하늘 씨. 어서 와요.', 'Bangawoyo, Haneul ssi. Eoseo wayo.', 'Nice to meet you, Haneul. Come on in.'),
        line('민준', '우리 엄마 요리 정말 맛있어요!', 'Uri eomma yori jeongmal masisseoyo!', 'My mom’s cooking is really good!'),
        line('하늘', '와! 잘 먹겠습니다.', 'Wa! Jal meokgetseumnida.', 'Wow! Thank you for the meal.'),
        line('하늘', '(after dinner) 잘 먹었습니다. 감사합니다!', 'Jal meogeotseumnida. Gamsahamnida!', 'I enjoyed the meal. Thank you!'),
        line('어머니', '아니에요. 또 와요.', 'Anieyo. Tto wayo.', 'Not at all. Come again.'),
        line('하늘', '안녕히 계세요!', 'Annyeonghi gyeseyo!', 'Goodbye! (I’m leaving)'),
        line('민준', '잘 가요, 하늘 씨! 또 봐요!', 'Jal gayo, Haneul ssi! Tto bwayo!', 'Bye, Haneul! See you!'),
      ],
    },
    pronunciation: {
      focus_en: '-ㅂ니다 always sounds [-ㅁ니다]: 감사합니다 [감사함니다].',
      items: [p('안녕하세요?', 'annyeonghaseyo?'), p('처음 뵙겠습니다', 'cheoeum boepgetseumnida', '[처음 뵙껟씀니다]'), p('만나서 반가워요', 'mannaseo bangawoyo'), p('감사합니다', 'gamsahamnida', '[감사함니다]'), p('죄송합니다', 'joesonghamnida', '[죄송함니다]'), p('괜찮아요', 'gwaenchanayo', '[괜차나요]'), p('잘 먹겠습니다', 'jal meokgetseumnida', '[잘 먹껟씀니다]'), p('생일 축하해요', 'saengil chukahaeyo', '[생일 추카해요]'), p('안녕히 계세요', 'annyeonghi gyeseyo')],
    },
    quiz: [
      mc('You meet your friend’s grandfather for the first time. Best greeting?', ['안녕!', '처음 뵙겠습니다.', '잘 가요.'], 1),
      mc('Someone says 감사합니다. You reply:', ['아니에요.', '죄송합니다.', '잘 먹었습니다.'], 0),
      mc('You are about to start eating. You say:', ['잘 먹었습니다.', '잘 먹겠습니다.', '생일 축하해요.'], 1),
      mc('Your friend is leaving your house. You say:', ['안녕히 가세요.', '안녕히 계세요.'], 0),
      mc('You bumped into someone. You say:', ['괜찮아요.', '죄송합니다.', '고마워요.'], 1),
      listen('생일 축하해요', ['생일 축하해요', '잘 먹겠습니다', '만나서 반가워요'], 0),
      mc('How is 감사합니다 pronounced?', ['[감사합니다]', '[감사함니다]', '[감사하니다]'], 1),
      order('Nice to meet you.', ['만나서', '반가워요.']),
    ],
    writing: { tip_en: 'Put a space between words: 만나서 반가워요.', items: [w('안녕하세요', 'annyeonghaseyo', 'hello'), w('감사합니다', 'gamsahamnida', 'thank you'), w('괜찮아요', 'gwaenchanayo', 'it’s okay'), w('잘 먹겠습니다', 'jal meokgetseumnida', 'thanks for the food'), w('또 봐요', 'tto bwayo', 'see you')] },
    culture: { title: 'Greetings and bowing', body_en: 'A light bow with 안녕하세요 is the normal greeting for teachers, adults and new people. At meals, Koreans say 잘 먹겠습니다 before eating and 잘 먹었습니다 after — a thank-you to whoever made or paid for the food.' },
    chat: {
      scenario: 'Practice greeting situations with Bori: meeting for the first time, thanking, apologizing, mealtime phrases and saying goodbye. Bori sets up a tiny situation in one short Korean sentence (with English help), then waits for the student’s greeting. Use only very simple Korean.',
      goal_en: 'Use the right greeting for each situation (처음 뵙겠습니다, 감사합니다, 죄송합니다, 잘 먹겠습니다, 안녕히 가세요/계세요).',
      starter_ko: '안녕하세요! 처음 만났어요. 뭐라고 말해요?',
      vocab: ['안녕하세요', '처음 뵙겠습니다', '반가워요', '감사합니다', '죄송합니다', '괜찮아요', '잘 먹겠습니다', '안녕히 가세요', '안녕히 계세요'],
    },
  },
];

export const seedLessons = [...lessons, ...bonusLessons];
